/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#if !defined(LAYER_FLAG_BITS_METADATA) || defined(IMPLEMENT_MANAGER)
#define LAYER_FLAG_BITS_METADATA

#include <3d/ecs/components/layer_defines.h>
#include <core/property_tools/core_metadata.inl>

CORE_BEGIN_NAMESPACE()
ENUM_TYPE_METADATA(CORE3D_NS::LayerFlagBits, ENUM_VALUE(CORE_LAYER_FLAG_BIT_00, "Layer 0"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_01, "Layer 1"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_02, "Layer 2"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_03, "Layer 3"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_04, "Layer 4"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_05, "Layer 5"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_06, "Layer 6"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_07, "Layer 7"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_08, "Layer 8"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_09, "Layer 9"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_10, "Layer 10"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_11, "Layer 11"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_12, "Layer 12"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_13, "Layer 13"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_14, "Layer 14"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_15, "Layer 15"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_16, "Layer 16"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_17, "Layer 17"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_18, "Layer 18"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_19, "Layer 19"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_20, "Layer 20"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_21, "Layer 21"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_22, "Layer 22"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_23, "Layer 23"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_24, "Layer 24"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_25, "Layer 25"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_26, "Layer 26"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_27, "Layer 27"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_28, "Layer 28"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_29, "Layer 29"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_30, "Layer 30"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_31, "Layer 31"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_32, "Layer 32"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_33, "Layer 33"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_34, "Layer 34"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_35, "Layer 35"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_36, "Layer 36"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_37, "Layer 37"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_38, "Layer 38"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_39, "Layer 39"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_40, "Layer 40"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_41, "Layer 41"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_42, "Layer 42"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_43, "Layer 43"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_44, "Layer 44"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_45, "Layer 45"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_46, "Layer 46"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_47, "Layer 47"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_48, "Layer 48"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_49, "Layer 49"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_50, "Layer 50"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_51, "Layer 51"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_52, "Layer 52"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_53, "Layer 53"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_54, "Layer 54"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_55, "Layer 55"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_56, "Layer 56"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_57, "Layer 57"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_58, "Layer 58"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_59, "Layer 59"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_60, "Layer 60"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_61, "Layer 61"), ENUM_VALUE(CORE_LAYER_FLAG_BIT_62, "Layer 62"),
    ENUM_VALUE(CORE_LAYER_FLAG_BIT_63, "Layer 63"))
CORE_END_NAMESPACE()
#endif // LAYER_FLAG_BITS_METADATA
