// $Copyright
//
// This header is generated from the Maleoon JSON Registry.
//

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

// Maleoon hardcoded constants - not an enumerated type, part of the header
// boilerplate

// API result codes
typedef enum MlnStatus {
    MLN_STATUS_SUCCESS = 0,
    MLN_STATUS_NOT_READY = 1,
    MLN_STATUS_TIMEOUT = 2,
    MLN_STATUS_INCOMPLETE = 3,
    MLN_STATUS_SUBOPTIMAL = 4,
    MLN_STATUS_OUT_OF_HOST_MEMORY = -1,
    MLN_STATUS_OUT_OF_DEVICE_MEMORY = -2,
    MLN_STATUS_INITIALIZATION_FAILED = -3,
    MLN_STATUS_DEVICE_LOST = -4,
    MLN_STATUS_MEMORY_MAP_FAILED = -5,
    MLN_STATUS_OBJECT_CREATION_FAILED = -6,
    MLN_STATUS_OBJECT_UPDATE_FAILED = -7,
    MLN_STATUS_INVALID_OBJECT_STATE = -8,
    MLN_STATUS_UNSUPPORTED = -9,
    MLN_STATUS_DATAGRAPH_DEPENDENCY_FAILED = -10,
    MLN_STATUS_OBJECT_MISMATCH = -11,
    MLN_STATUS_LAYER_NOT_PRESENT = -12,
    MLN_STATUS_FEATURE_NOT_PRESENT = -13,
    MLN_STATUS_INCOMPATIBLE_DRIVER = -14,
    MLN_STATUS_FORMAT_NOT_SUPPORTED = -15,
    MLN_STATUS_UNKNOWN = -16,
    MLN_STATUS_NOT_PERMITTED = -17,
    MLN_STATUS_INVALID_EXTERNAL_HANDLE = -18,
    MLN_STATUS_INVALID_OPAQUE_CAPTURE_ADDRESS = -19,
    MLN_STATUS_VALIDATION_FAILED = -20,
    MLN_STATUS_INVALID_ARGUMENT = -21,
    MLN_STATUS_SURFACE_LOST = -22,
    MLN_STATUS_NATIVE_WINDOW_IN_USE = -23,
    MLN_STATUS_OUT_OF_DATE = -24,
    MLN_STATUS_MAX_ENUM = 0x7FFFFFFF
} MlnStatus;

typedef enum MlnObjectType {
    MLN_OBJECT_TYPE_UNKNOWN = 0,
    MLN_OBJECT_TYPE_DEVICE = 1,
    MLN_OBJECT_TYPE_QUEUE = 2,
    MLN_OBJECT_TYPE_DEVICE_MEMORY = 3,
    MLN_OBJECT_TYPE_RESOURCE = 4,
    MLN_OBJECT_TYPE_RESOURCE_VIEW = 5,
    MLN_OBJECT_TYPE_SAMPLER = 6,
    MLN_OBJECT_TYPE_SHADER = 7,
    MLN_OBJECT_TYPE_PROGRAM_CACHE = 8,
    MLN_OBJECT_TYPE_PROGRAM_INTERFACE = 9,
    MLN_OBJECT_TYPE_PROGRAM = 10,
    MLN_OBJECT_TYPE_BINDING_LAYOUT = 11,
    MLN_OBJECT_TYPE_BINDING_SET = 12,
    MLN_OBJECT_TYPE_OBJECT_GROUP = 13,
    MLN_OBJECT_TYPE_DATA_GRAPH = 14,
    MLN_OBJECT_TYPE_SCHEDULING_GRAPH = 15,
    MLN_OBJECT_TYPE_TIMELINE = 16,
    MLN_OBJECT_TYPE_RENDER_TARGET = 17,
    MLN_OBJECT_TYPE_DISPLAY_SURFACE = 18,
    MLN_OBJECT_TYPE_SWAPCHAIN = 19,
    MLN_OBJECT_TYPE_ACCELERATION_STRUCTURE = 20,
    MLN_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION = 21,
    MLN_OBJECT_TYPE_PRIVATE_DATA_SLOT = 22,
    MLN_OBJECT_TYPE_QUERY_POOL = 23,
    MLN_OBJECT_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnObjectType;

typedef enum MlnExtensionKey {
    MLN_EXTENSION_KEY_NONE = 0,
    MLN_EXTENSION_KEY_VALIDATION_LAYER = 1,
    MLN_EXTENSION_KEY_MAX_ENUM = 0x7FFFFFFF
} MlnExtensionKey;

typedef enum MlnFragmentShadingRateCombinerOp {
    MLN_FRAGMENT_SHADING_RATE_COMBINER_OP_KEEP = 0,
    MLN_FRAGMENT_SHADING_RATE_COMBINER_OP_REPLACE = 1,
    MLN_FRAGMENT_SHADING_RATE_COMBINER_OP_MIN = 2,
    MLN_FRAGMENT_SHADING_RATE_COMBINER_OP_MAX = 3,
    MLN_FRAGMENT_SHADING_RATE_COMBINER_OP_MUL = 4,
    MLN_FRAGMENT_SHADING_RATE_COMBINER_OP_MAX_ENUM = 0x7FFFFFFF
} MlnFragmentShadingRateCombinerOp;

typedef enum MlnLayerFlag {
    MLN_LAYER_FLAG_NONE = 0,
    MLN_LAYER_FLAG_MAX_ENUM = 0x7FFFFFFF
} MlnLayerFlag;

typedef enum MlnDeviceDescriptorFlagBits {
    MLN_DEVICE_DESCRIPTOR_HTS_ENABLE_BIT = 0x00000001,
    MLN_DEVICE_DESCRIPTOR_VALIDATION_BIT = 0x00000002,
    MLN_DEVICE_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnDeviceDescriptorFlagBits;

typedef enum MlnValidationLayerFlagBits {
    MLN_VALIDATION_LAYER_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnValidationLayerFlagBits;

typedef enum MlnValidationLayerLogType {
    MLN_VALIDATION_LAYER_LOG_TYPE_STDOUT = 0x00000000,
    MLN_VALIDATION_LAYER_LOG_TYPE_HILOG = 0x00000001,
    MLN_VALIDATION_LAYER_LOG_TYPE_FILE = 0x00000002,
    MLN_VALIDATION_LAYER_LOG_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnValidationLayerLogType;

typedef enum MlnValidationLayerReportLevel {
    MLN_VALIDATION_LAYER_REPORT_LEVEL_INFO = 0x00000000,
    MLN_VALIDATION_LAYER_REPORT_LEVEL_WARN = 0x00000001,
    MLN_VALIDATION_LAYER_REPORT_LEVEL_ERROR = 0x00000002,
    MLN_VALIDATION_LAYER_REPORT_LEVEL_FATAL_ERROR = 0x00000003,
    MLN_VALIDATION_LAYER_REPORT_LEVEL_MAX_ENUM = 0x7FFFFFFF
} MlnValidationLayerReportLevel;

typedef enum MlnValidationLayerCheckActionType {
    MLN_VALIDATION_LAYER_CHECK_ACTION_TYPE_CONTINUE = 0x00000000,
    MLN_VALIDATION_LAYER_CHECK_ACTION_TYPE_EARLY_RETURN = 0x00000001,
    MLN_VALIDATION_LAYER_CHECK_ACTION_TYPE_ABORT = 0x00000002,
    MLN_VALIDATION_LAYER_CHECK_ACTION_MAX_ENUM = 0x7FFFFFFF
} MlnValidationLayerCheckActionType;

typedef enum MlnValidationLayerCheckOptionFlagBits {
    MLN_VALIDATION_LAYER_CHECK_OPTION_CORE_API_BIT = 0x00000001,
    MLN_VALIDATION_LAYER_CHECK_OPTION_OBJECT_LIFECYCLE_BIT = 0x00000002,
    MLN_VALIDATION_LAYER_CHECK_OPTION_SYNCRONIZATION_BIT = 0x00000004,
    MLN_VALIDATION_LAYER_CHECK_OPTION_SHADER_BIT = 0x00000008,
    MLN_VALIDATION_LAYER_CHECK_OPTION_SHADER_API_CROSS_CHECK_BIT = 0x00000010,
    MLN_VALIDATION_LAYER_CHECK_OPTION_BEST_PRACTICE_BIT = 0x00000020,
    MLN_VALIDATION_LAYER_CHECK_OPTION_API_DUMP_BIT = 0x00000040,
    MLN_VALIDATION_LAYER_CHECK_OPTION_MAX_ENUM = 0x7FFFFFFF
} MlnValidationLayerCheckOptionFlagBits;

typedef enum MlnQueuePriority {
    MLN_QUEUE_PRIORITY_LOW = 128,
    MLN_QUEUE_PRIORITY_MEDIUM = 256,
    MLN_QUEUE_PRIORITY_HIGH = 512,
    MLN_QUEUE_PRIORITY_REALTIME = 1024,
    MLN_QUEUE_PRIORITY_MAX_ENUM = 0x7FFFFFFF
} MlnQueuePriority;

typedef enum MlnQueueDescriptorFlagBits {
    MLN_QUEUE_DESCRIPTOR_PROTECTED_BIT = 0x00000001,
    MLN_QUEUE_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnQueueDescriptorFlagBits;

typedef enum MlnSubmitDescriptorFlagBits {
    MLN_SUBMIT_DESCRIPTOR_PROTECTED_BIT = 0x00000001,
    MLN_SUBMIT_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnSubmitDescriptorFlagBits;

typedef enum MlnMemoryHeapFlagBits {
    MLN_MEMORY_HEAP_DEVICE_LOCAL_BIT = 0x00000001,
    MLN_MEMORY_HEAP_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnMemoryHeapFlagBits;

typedef enum MlnMemoryPropertyFlagBits {
    MLN_MEMORY_PROPERTY_DEVICE_LOCAL_BIT = 0x00000001,
    MLN_MEMORY_PROPERTY_HOST_VISIBLE_BIT = 0x00000002,
    MLN_MEMORY_PROPERTY_HOST_COHERENT_BIT = 0x00000004,
    MLN_MEMORY_PROPERTY_HOST_CACHED_BIT = 0x00000008,
    MLN_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT = 0x00000010,
    MLN_MEMORY_PROPERTY_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnMemoryPropertyFlagBits;

typedef enum MlnMemoryMapDescriptorFlagBits {
    MLN_MEMORY_MAP_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnMemoryMapDescriptorFlagBits;

typedef enum MlnMemoryUnmapDescriptorFlagBits {
    MLN_MEMORY_UNMAP_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnMemoryUnmapDescriptorFlagBits;

typedef enum MlnExternalMemoryHandleType {
    MLN_EXTERNAL_MEMORY_HANDLE_TYPE_NONE = 0,
    MLN_EXTERNAL_MEMORY_HANDLE_TYPE_NATIVE_BUFFER = 1,
    MLN_EXTERNAL_MEMORY_HANDLE_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnExternalMemoryHandleType;

typedef enum MlnMemoryPolicy {
    MLN_MEMORY_POLICY_NONE = 0,
    MLN_MEMORY_POLICY_READ_DEALLOCATE_INVALID = 1,
    MLN_MEMORY_POLICY_READ_DEALLOCATE_CLEAN_INVALID = 2,
    MLN_MEMORY_POLICY_MAX_ENUM = 0x7FFFFFFF
} MlnMemoryPolicy;

typedef enum MlnBufferUsageFlagBits {
    MLN_BUFFER_USAGE_TRANSFER_SRC_BIT = 0x00000001,
    MLN_BUFFER_USAGE_TRANSFER_DST_BIT = 0x00000002,
    MLN_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT = 0x00000004,
    MLN_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT = 0x00000008,
    MLN_BUFFER_USAGE_UNIFORM_BUFFER_BIT = 0x00000010,
    MLN_BUFFER_USAGE_STORAGE_BUFFER_BIT = 0x00000020,
    MLN_BUFFER_USAGE_INDEX_BUFFER_BIT = 0x00000040,
    MLN_BUFFER_USAGE_VERTEX_BUFFER_BIT = 0x00000080,
    MLN_BUFFER_USAGE_INDIRECT_BUFFER_BIT = 0x00000100,
    MLN_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT = 0x00000200,
    MLN_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT = 0x00000400,
    MLN_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT =
        0x00000800,
    MLN_BUFFER_USAGE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnBufferUsageFlagBits;

typedef enum MlnBufferDescriptorFlagBits {
    MLN_BUFFER_DESCRIPTOR_SPARSE_BINDING_BIT = 0x00000001,
    MLN_BUFFER_DESCRIPTOR_SPARSE_RESIDENCY_BIT = 0x00000002,
    MLN_BUFFER_DESCRIPTOR_SPARSE_ALIASED_BIT = 0x00000004,
    MLN_BUFFER_DESCRIPTOR_PROTECTED_BIT = 0x00000008,
    MLN_BUFFER_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnBufferDescriptorFlagBits;

typedef enum MlnImageType {
    MLN_IMAGE_TYPE_1D = 0,
    MLN_IMAGE_TYPE_2D = 1,
    MLN_IMAGE_TYPE_3D = 2,
    MLN_IMAGE_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnImageType;

// Maleoon format definitions
typedef enum MlnFormat {
    MLN_FORMAT_UNDEFINED = 0,
    MLN_FORMAT_R4G4_UNORM_PACK8 = 1,
    MLN_FORMAT_R4G4B4A4_UNORM_PACK16 = 2,
    MLN_FORMAT_B4G4R4A4_UNORM_PACK16 = 3,
    MLN_FORMAT_R5G6B5_UNORM_PACK16 = 4,
    MLN_FORMAT_B5G6R5_UNORM_PACK16 = 5,
    MLN_FORMAT_R5G5B5A1_UNORM_PACK16 = 6,
    MLN_FORMAT_B5G5R5A1_UNORM_PACK16 = 7,
    MLN_FORMAT_A1R5G5B5_UNORM_PACK16 = 8,
    MLN_FORMAT_R8_UNORM = 9,
    MLN_FORMAT_R8_SNORM = 10,
    MLN_FORMAT_R8_USCALED = 11,
    MLN_FORMAT_R8_SSCALED = 12,
    MLN_FORMAT_R8_UINT = 13,
    MLN_FORMAT_R8_SINT = 14,
    MLN_FORMAT_R8_SRGB = 15,
    MLN_FORMAT_R8G8_UNORM = 16,
    MLN_FORMAT_R8G8_SNORM = 17,
    MLN_FORMAT_R8G8_USCALED = 18,
    MLN_FORMAT_R8G8_SSCALED = 19,
    MLN_FORMAT_R8G8_UINT = 20,
    MLN_FORMAT_R8G8_SINT = 21,
    MLN_FORMAT_R8G8_SRGB = 22,
    MLN_FORMAT_R8G8B8_UNORM = 23,
    MLN_FORMAT_R8G8B8_SNORM = 24,
    MLN_FORMAT_R8G8B8_USCALED = 25,
    MLN_FORMAT_R8G8B8_SSCALED = 26,
    MLN_FORMAT_R8G8B8_UINT = 27,
    MLN_FORMAT_R8G8B8_SINT = 28,
    MLN_FORMAT_R8G8B8_SRGB = 29,
    MLN_FORMAT_B8G8R8_UNORM = 30,
    MLN_FORMAT_B8G8R8_SNORM = 31,
    MLN_FORMAT_B8G8R8_USCALED = 32,
    MLN_FORMAT_B8G8R8_SSCALED = 33,
    MLN_FORMAT_B8G8R8_UINT = 34,
    MLN_FORMAT_B8G8R8_SINT = 35,
    MLN_FORMAT_B8G8R8_SRGB = 36,
    MLN_FORMAT_R8G8B8A8_UNORM = 37,
    MLN_FORMAT_R8G8B8A8_SNORM = 38,
    MLN_FORMAT_R8G8B8A8_USCALED = 39,
    MLN_FORMAT_R8G8B8A8_SSCALED = 40,
    MLN_FORMAT_R8G8B8A8_UINT = 41,
    MLN_FORMAT_R8G8B8A8_SINT = 42,
    MLN_FORMAT_R8G8B8A8_SRGB = 43,
    MLN_FORMAT_B8G8R8A8_UNORM = 44,
    MLN_FORMAT_B8G8R8A8_SNORM = 45,
    MLN_FORMAT_B8G8R8A8_USCALED = 46,
    MLN_FORMAT_B8G8R8A8_SSCALED = 47,
    MLN_FORMAT_B8G8R8A8_UINT = 48,
    MLN_FORMAT_B8G8R8A8_SINT = 49,
    MLN_FORMAT_B8G8R8A8_SRGB = 50,
    MLN_FORMAT_A8B8G8R8_UNORM_PACK32 = 51,
    MLN_FORMAT_A8B8G8R8_SNORM_PACK32 = 52,
    MLN_FORMAT_A8B8G8R8_USCALED_PACK32 = 53,
    MLN_FORMAT_A8B8G8R8_SSCALED_PACK32 = 54,
    MLN_FORMAT_A8B8G8R8_UINT_PACK32 = 55,
    MLN_FORMAT_A8B8G8R8_SINT_PACK32 = 56,
    MLN_FORMAT_A8B8G8R8_SRGB_PACK32 = 57,
    MLN_FORMAT_A2R10G10B10_UNORM_PACK32 = 58,
    MLN_FORMAT_A2R10G10B10_SNORM_PACK32 = 59,
    MLN_FORMAT_A2R10G10B10_USCALED_PACK32 = 60,
    MLN_FORMAT_A2R10G10B10_SSCALED_PACK32 = 61,
    MLN_FORMAT_A2R10G10B10_UINT_PACK32 = 62,
    MLN_FORMAT_A2R10G10B10_SINT_PACK32 = 63,
    MLN_FORMAT_A2B10G10R10_UNORM_PACK32 = 64,
    MLN_FORMAT_A2B10G10R10_SNORM_PACK32 = 65,
    MLN_FORMAT_A2B10G10R10_USCALED_PACK32 = 66,
    MLN_FORMAT_A2B10G10R10_SSCALED_PACK32 = 67,
    MLN_FORMAT_A2B10G10R10_UINT_PACK32 = 68,
    MLN_FORMAT_A2B10G10R10_SINT_PACK32 = 69,
    MLN_FORMAT_R16_UNORM = 70,
    MLN_FORMAT_R16_SNORM = 71,
    MLN_FORMAT_R16_USCALED = 72,
    MLN_FORMAT_R16_SSCALED = 73,
    MLN_FORMAT_R16_UINT = 74,
    MLN_FORMAT_R16_SINT = 75,
    MLN_FORMAT_R16_SFLOAT = 76,
    MLN_FORMAT_R16G16_UNORM = 77,
    MLN_FORMAT_R16G16_SNORM = 78,
    MLN_FORMAT_R16G16_USCALED = 79,
    MLN_FORMAT_R16G16_SSCALED = 80,
    MLN_FORMAT_R16G16_UINT = 81,
    MLN_FORMAT_R16G16_SINT = 82,
    MLN_FORMAT_R16G16_SFLOAT = 83,
    MLN_FORMAT_R16G16B16_UNORM = 84,
    MLN_FORMAT_R16G16B16_SNORM = 85,
    MLN_FORMAT_R16G16B16_USCALED = 86,
    MLN_FORMAT_R16G16B16_SSCALED = 87,
    MLN_FORMAT_R16G16B16_UINT = 88,
    MLN_FORMAT_R16G16B16_SINT = 89,
    MLN_FORMAT_R16G16B16_SFLOAT = 90,
    MLN_FORMAT_R16G16B16A16_UNORM = 91,
    MLN_FORMAT_R16G16B16A16_SNORM = 92,
    MLN_FORMAT_R16G16B16A16_USCALED = 93,
    MLN_FORMAT_R16G16B16A16_SSCALED = 94,
    MLN_FORMAT_R16G16B16A16_UINT = 95,
    MLN_FORMAT_R16G16B16A16_SINT = 96,
    MLN_FORMAT_R16G16B16A16_SFLOAT = 97,
    MLN_FORMAT_R32_UINT = 98,
    MLN_FORMAT_R32_SINT = 99,
    MLN_FORMAT_R32_SFLOAT = 100,
    MLN_FORMAT_R32G32_UINT = 101,
    MLN_FORMAT_R32G32_SINT = 102,
    MLN_FORMAT_R32G32_SFLOAT = 103,
    MLN_FORMAT_R32G32B32_UINT = 104,
    MLN_FORMAT_R32G32B32_SINT = 105,
    MLN_FORMAT_R32G32B32_SFLOAT = 106,
    MLN_FORMAT_R32G32B32A32_UINT = 107,
    MLN_FORMAT_R32G32B32A32_SINT = 108,
    MLN_FORMAT_R32G32B32A32_SFLOAT = 109,
    MLN_FORMAT_R64_UINT = 110,
    MLN_FORMAT_R64_SINT = 111,
    MLN_FORMAT_R64_SFLOAT = 112,
    MLN_FORMAT_R64G64_UINT = 113,
    MLN_FORMAT_R64G64_SINT = 114,
    MLN_FORMAT_R64G64_SFLOAT = 115,
    MLN_FORMAT_R64G64B64_UINT = 116,
    MLN_FORMAT_R64G64B64_SINT = 117,
    MLN_FORMAT_R64G64B64_SFLOAT = 118,
    MLN_FORMAT_R64G64B64A64_UINT = 119,
    MLN_FORMAT_R64G64B64A64_SINT = 120,
    MLN_FORMAT_R64G64B64A64_SFLOAT = 121,
    MLN_FORMAT_B10G11R11_UFLOAT_PACK32 = 122,
    MLN_FORMAT_E5B9G9R9_UFLOAT_PACK32 = 123,
    MLN_FORMAT_D16_UNORM = 124,
    MLN_FORMAT_X8_D24_UNORM_PACK32 = 125,
    MLN_FORMAT_D32_SFLOAT = 126,
    MLN_FORMAT_S8_UINT = 127,
    MLN_FORMAT_D16_UNORM_S8_UINT = 128,
    MLN_FORMAT_D24_UNORM_S8_UINT = 129,
    MLN_FORMAT_D32_SFLOAT_S8_UINT = 130,
    MLN_FORMAT_BC1_RGB_UNORM_BLOCK = 131,
    MLN_FORMAT_BC1_RGB_SRGB_BLOCK = 132,
    MLN_FORMAT_BC1_RGBA_UNORM_BLOCK = 133,
    MLN_FORMAT_BC1_RGBA_SRGB_BLOCK = 134,
    MLN_FORMAT_BC2_UNORM_BLOCK = 135,
    MLN_FORMAT_BC2_SRGB_BLOCK = 136,
    MLN_FORMAT_BC3_UNORM_BLOCK = 137,
    MLN_FORMAT_BC3_SRGB_BLOCK = 138,
    MLN_FORMAT_BC4_UNORM_BLOCK = 139,
    MLN_FORMAT_BC4_SNORM_BLOCK = 140,
    MLN_FORMAT_BC5_UNORM_BLOCK = 141,
    MLN_FORMAT_BC5_SNORM_BLOCK = 142,
    MLN_FORMAT_BC6H_UFLOAT_BLOCK = 143,
    MLN_FORMAT_BC6H_SFLOAT_BLOCK = 144,
    MLN_FORMAT_BC7_UNORM_BLOCK = 145,
    MLN_FORMAT_BC7_SRGB_BLOCK = 146,
    MLN_FORMAT_ETC2_R8G8B8_UNORM_BLOCK = 147,
    MLN_FORMAT_ETC2_R8G8B8_SRGB_BLOCK = 148,
    MLN_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK = 149,
    MLN_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK = 150,
    MLN_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK = 151,
    MLN_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK = 152,
    MLN_FORMAT_EAC_R11_UNORM_BLOCK = 153,
    MLN_FORMAT_EAC_R11_SNORM_BLOCK = 154,
    MLN_FORMAT_EAC_R11G11_UNORM_BLOCK = 155,
    MLN_FORMAT_EAC_R11G11_SNORM_BLOCK = 156,
    MLN_FORMAT_ASTC_4x4_UNORM_BLOCK = 157,
    MLN_FORMAT_ASTC_4x4_SRGB_BLOCK = 158,
    MLN_FORMAT_ASTC_5x4_UNORM_BLOCK = 159,
    MLN_FORMAT_ASTC_5x4_SRGB_BLOCK = 160,
    MLN_FORMAT_ASTC_5x5_UNORM_BLOCK = 161,
    MLN_FORMAT_ASTC_5x5_SRGB_BLOCK = 162,
    MLN_FORMAT_ASTC_6x5_UNORM_BLOCK = 163,
    MLN_FORMAT_ASTC_6x5_SRGB_BLOCK = 164,
    MLN_FORMAT_ASTC_6x6_UNORM_BLOCK = 165,
    MLN_FORMAT_ASTC_6x6_SRGB_BLOCK = 166,
    MLN_FORMAT_ASTC_8x5_UNORM_BLOCK = 167,
    MLN_FORMAT_ASTC_8x5_SRGB_BLOCK = 168,
    MLN_FORMAT_ASTC_8x6_UNORM_BLOCK = 169,
    MLN_FORMAT_ASTC_8x6_SRGB_BLOCK = 170,
    MLN_FORMAT_ASTC_8x8_UNORM_BLOCK = 171,
    MLN_FORMAT_ASTC_8x8_SRGB_BLOCK = 172,
    MLN_FORMAT_ASTC_10x5_UNORM_BLOCK = 173,
    MLN_FORMAT_ASTC_10x5_SRGB_BLOCK = 174,
    MLN_FORMAT_ASTC_10x6_UNORM_BLOCK = 175,
    MLN_FORMAT_ASTC_10x6_SRGB_BLOCK = 176,
    MLN_FORMAT_ASTC_10x8_UNORM_BLOCK = 177,
    MLN_FORMAT_ASTC_10x8_SRGB_BLOCK = 178,
    MLN_FORMAT_ASTC_10x10_UNORM_BLOCK = 179,
    MLN_FORMAT_ASTC_10x10_SRGB_BLOCK = 180,
    MLN_FORMAT_ASTC_12x10_UNORM_BLOCK = 181,
    MLN_FORMAT_ASTC_12x10_SRGB_BLOCK = 182,
    MLN_FORMAT_ASTC_12x12_UNORM_BLOCK = 183,
    MLN_FORMAT_ASTC_12x12_SRGB_BLOCK = 184,
    MLN_FORMAT_ASTC_4x4_SFLOAT_BLOCK = 185,
    MLN_FORMAT_ASTC_5x4_SFLOAT_BLOCK = 186,
    MLN_FORMAT_ASTC_5x5_SFLOAT_BLOCK = 187,
    MLN_FORMAT_ASTC_6x5_SFLOAT_BLOCK = 188,
    MLN_FORMAT_ASTC_6x6_SFLOAT_BLOCK = 189,
    MLN_FORMAT_ASTC_8x5_SFLOAT_BLOCK = 190,
    MLN_FORMAT_ASTC_8x6_SFLOAT_BLOCK = 191,
    MLN_FORMAT_ASTC_8x8_SFLOAT_BLOCK = 192,
    MLN_FORMAT_ASTC_10x5_SFLOAT_BLOCK = 193,
    MLN_FORMAT_ASTC_10x6_SFLOAT_BLOCK = 194,
    MLN_FORMAT_ASTC_10x8_SFLOAT_BLOCK = 195,
    MLN_FORMAT_ASTC_10x10_SFLOAT_BLOCK = 196,
    MLN_FORMAT_ASTC_12x10_SFLOAT_BLOCK = 197,
    MLN_FORMAT_ASTC_12x12_SFLOAT_BLOCK = 198,
    MLN_FORMAT_G8B8G8R8_422_UNORM = 200,
    MLN_FORMAT_B8G8R8G8_422_UNORM = 201,
    MLN_FORMAT_G8_B8_R8_3PLANE_420_UNORM = 202,
    MLN_FORMAT_G8_B8R8_2PLANE_420_UNORM = 203,
    MLN_FORMAT_G8_B8_R8_3PLANE_422_UNORM = 204,
    MLN_FORMAT_G8_B8R8_2PLANE_422_UNORM = 205,
    MLN_FORMAT_G8_B8_R8_3PLANE_444_UNORM = 206,
    MLN_FORMAT_R10X6_UNORM_PACK16 = 207,
    MLN_FORMAT_R10X6G10X6_UNORM_2PACK16 = 208,
    MLN_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16 = 209,
    MLN_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16 = 210,
    MLN_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16 = 211,
    MLN_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16 = 212,
    MLN_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16 = 213,
    MLN_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16 = 214,
    MLN_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16 = 215,
    MLN_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16 = 216,
    MLN_FORMAT_A4R4G4B4_UNORM_PACK16 = 217,
    MLN_FORMAT_A4B4G4R4_UNORM_PACK16 = 218,
    MLN_FORMAT_A8_UNORM = 219,
    MLN_FORMAT_ASTC_3x3x3_UNORM_BLOCK = 221,
    MLN_FORMAT_ASTC_4x3x3_UNORM_BLOCK = 222,
    MLN_FORMAT_ASTC_4x4x3_UNORM_BLOCK = 223,
    MLN_FORMAT_ASTC_4x4x4_UNORM_BLOCK = 224,
    MLN_FORMAT_ASTC_5x4x4_UNORM_BLOCK = 225,
    MLN_FORMAT_ASTC_5x5x4_UNORM_BLOCK = 226,
    MLN_FORMAT_ASTC_5x5x5_UNORM_BLOCK = 227,
    MLN_FORMAT_ASTC_6x5x5_UNORM_BLOCK = 228,
    MLN_FORMAT_ASTC_6x6x5_UNORM_BLOCK = 229,
    MLN_FORMAT_ASTC_6x6x6_UNORM_BLOCK = 230,
    MLN_FORMAT_ASTC_3x3x3_SFLOAT_BLOCK = 231,
    MLN_FORMAT_ASTC_4x3x3_SFLOAT_BLOCK = 232,
    MLN_FORMAT_ASTC_4x4x3_SFLOAT_BLOCK = 233,
    MLN_FORMAT_ASTC_4x4x4_SFLOAT_BLOCK = 234,
    MLN_FORMAT_ASTC_5x4x4_SFLOAT_BLOCK = 235,
    MLN_FORMAT_ASTC_5x5x4_SFLOAT_BLOCK = 236,
    MLN_FORMAT_ASTC_5x5x5_SFLOAT_BLOCK = 237,
    MLN_FORMAT_ASTC_6x5x5_SFLOAT_BLOCK = 238,
    MLN_FORMAT_ASTC_6x6x5_SFLOAT_BLOCK = 239,
    MLN_FORMAT_ASTC_6x6x6_SFLOAT_BLOCK = 240,
    MLN_FORMAT_ASTC_3x3x3_SRGB8_BLOCK = 241,
    MLN_FORMAT_ASTC_4x3x3_SRGB8_BLOCK = 242,
    MLN_FORMAT_ASTC_4x4x3_SRGB8_BLOCK = 243,
    MLN_FORMAT_ASTC_4x4x4_SRGB8_BLOCK = 244,
    MLN_FORMAT_ASTC_5x4x4_SRGB8_BLOCK = 245,
    MLN_FORMAT_ASTC_5x5x4_SRGB8_BLOCK = 246,
    MLN_FORMAT_ASTC_5x5x5_SRGB8_BLOCK = 247,
    MLN_FORMAT_ASTC_6x5x5_SRGB8_BLOCK = 248,
    MLN_FORMAT_ASTC_6x6x5_SRGB8_BLOCK = 249,
    MLN_FORMAT_ASTC_6x6x6_SRGB8_BLOCK = 250,
    MLN_FORMAT_X24_S8_UINT = 251,
    MLN_FORMAT_G8_B8R8_2PLANE_444_UNORM = 252,
    MLN_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16 = 253,
    MLN_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16 = 254,
    MLN_FORMAT_G16_B16R16_2PLANE_444_UNORM = 255,
    MLN_FORMAT_MAX_ENUM = 0x7FFFFFFF
} MlnFormat;

typedef enum MlnImageDescriptorFlagBits {
    MLN_IMAGE_DESCRIPTOR_CUBE_COMPATIBLE_BIT = 0x00000001,
    MLN_IMAGE_DESCRIPTOR_2D_ARRAY_COMPATIBLE_BIT = 0x00000002,
    MLN_IMAGE_DESCRIPTOR_MUTABLE_FORMAT_BIT = 0x00000004,
    MLN_IMAGE_DESCRIPTOR_EXTENDED_USAGE_BIT = 0x00000008,
    MLN_IMAGE_DESCRIPTOR_PROTECTED_BIT = 0x00000010,
    MLN_IMAGE_DESCRIPTOR_SPARSE_BINDING_BIT = 0x00000020,
    MLN_IMAGE_DESCRIPTOR_SPARSE_RESIDENCY_BIT = 0x00000040,
    MLN_IMAGE_DESCRIPTOR_SPARSE_ALIASED_BIT = 0x00000080,
    MLN_IMAGE_DESCRIPTOR_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT = 0x00000100,
    MLN_IMAGE_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnImageDescriptorFlagBits;

typedef enum MlnSampleCountFlagBits {
    MLN_SAMPLE_COUNT_1_BIT = 0x00000001,
    MLN_SAMPLE_COUNT_2_BIT = 0x00000002,
    MLN_SAMPLE_COUNT_4_BIT = 0x00000004,
    MLN_SAMPLE_COUNT_8_BIT = 0x00000008,
    MLN_SAMPLE_COUNT_16_BIT = 0x00000010,
    MLN_SAMPLE_COUNT_32_BIT = 0x00000020,
    MLN_SAMPLE_COUNT_64_BIT = 0x00000040,
    MLN_SAMPLE_COUNT_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnSampleCountFlagBits;

typedef enum MlnImageTiling {
    MLN_IMAGE_TILING_OPTIMAL = 0,
    MLN_IMAGE_TILING_LINEAR = 1,
    MLN_IMAGE_TILING_MAX_ENUM = 0x7FFFFFFF
} MlnImageTiling;

typedef enum MlnImageUsageFlagBits {
    MLN_IMAGE_USAGE_TRANSFER_SRC_BIT = 0x00000001,
    MLN_IMAGE_USAGE_TRANSFER_DST_BIT = 0x00000002,
    MLN_IMAGE_USAGE_SAMPLED_BIT = 0x00000004,
    MLN_IMAGE_USAGE_STORAGE_BIT = 0x00000008,
    MLN_IMAGE_USAGE_COLOR_ATTACHMENT_BIT = 0x00000010,
    MLN_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT = 0x00000020,
    MLN_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT = 0x00000040,
    MLN_IMAGE_USAGE_INPUT_ATTACHMENT_BIT = 0x00000080,
    MLN_IMAGE_USAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT = 0x00000100,
    MLN_IMAGE_USAGE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnImageUsageFlagBits;

typedef enum MlnImageLayout {
    MLN_IMAGE_LAYOUT_UNDEFINED = 0,
    MLN_IMAGE_LAYOUT_GENERAL = 1,
    MLN_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL = 2,
    MLN_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL = 3,
    MLN_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL = 4,
    MLN_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL = 5,
    MLN_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL = 6,
    MLN_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL = 7,
    MLN_IMAGE_LAYOUT_PREINITIALIZED = 8,
    MLN_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL = 9,
    MLN_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL = 10,
    MLN_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL = 11,
    MLN_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL = 12,
    MLN_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL = 13,
    MLN_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL = 14,
    MLN_IMAGE_LAYOUT_READ_ONLY_OPTIMAL = 15,
    MLN_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL = 16,
    MLN_IMAGE_LAYOUT_RENDERING_LOCAL_READ = 17,
    MLN_IMAGE_LAYOUT_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL = 18,
    MLN_IMAGE_LAYOUT_PRESENT_SRC = 19,
    MLN_IMAGE_LAYOUT_MAX_ENUM = 0x7FFFFFFF
} MlnImageLayout;

typedef enum MlnFormatFeatureFlagBits {
    MLN_FORMAT_FEATURE_SAMPLED_IMAGE_BIT = 0x00000001,
    MLN_FORMAT_FEATURE_STORAGE_IMAGE_BIT = 0x00000002,
    MLN_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT = 0x00000004,
    MLN_FORMAT_FEATURE_UNIFORM_TEXEL_BUFFER_BIT = 0x00000008,
    MLN_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_BIT = 0x00000010,
    MLN_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_ATOMIC_BIT = 0x00000020,
    MLN_FORMAT_FEATURE_VERTEX_BUFFER_BIT = 0x00000040,
    MLN_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT = 0x00000080,
    MLN_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT = 0x00000100,
    MLN_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT = 0x00000200,
    MLN_FORMAT_FEATURE_BLIT_SRC_BIT = 0x00000400,
    MLN_FORMAT_FEATURE_BLIT_DST_BIT = 0x00000800,
    MLN_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT = 0x00001000,
    MLN_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_MINMAX_BIT = 0x00002000,
    MLN_FORMAT_FEATURE_TRANSFER_SRC_BIT = 0x00004000,
    MLN_FORMAT_FEATURE_TRANSFER_DST_BIT = 0x00008000,
    MLN_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT = 0x00010000,
    MLN_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT =
        0x00020000,
    MLN_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT =
        0x00040000,
    MLN_FORMAT_FEATURE_DISJOINT_BIT = 0x00080000,
    MLN_FORMAT_FEATURE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT = 0x00100000,
    MLN_FORMAT_FEATURE_STORAGE_READ_WITHOUT_FORMAT_BIT = 0x00200000,
    MLN_FORMAT_FEATURE_STORAGE_WRITE_WITHOUT_FORMAT_BIT = 0x00400000,
    MLN_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT = 0x00800000,
    MLN_FORMAT_FEATURE_ACCELERATION_STRUCTURE_VERTEX_BUFFER_BIT = 0x01000000,
    MLN_FORMAT_FEATURE_SAMPLED_IMAGE_DEPTH_COMPARISON_BIT = 0x02000000,
    MLN_FORMAT_FEATURE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnFormatFeatureFlagBits;

typedef enum MlnFilter {
    MLN_FILTER_NEAREST = 0,
    MLN_FILTER_LINEAR = 1,
    MLN_FILTER_MAX_ENUM = 0x7FFFFFFF
} MlnFilter;

typedef enum MlnSamplerMipmapMode {
    MLN_SAMPLER_MIPMAP_MODE_NEAREST = 0,
    MLN_SAMPLER_MIPMAP_MODE_LINEAR = 1,
    MLN_SAMPLER_MIPMAP_MODE_MAX_ENUM = 0x7FFFFFFF
} MlnSamplerMipmapMode;

typedef enum MlnSamplerAddressMode {
    MLN_SAMPLER_ADDRESS_MODE_REPEAT = 0,
    MLN_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT = 1,
    MLN_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE = 2,
    MLN_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER = 3,
    MLN_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE = 4,
    MLN_SAMPLER_ADDRESS_MODE_MAX_ENUM = 0x7FFFFFFF
} MlnSamplerAddressMode;

typedef enum MlnCompareOp {
    MLN_COMPARE_OP_NEVER = 0,
    MLN_COMPARE_OP_LESS = 1,
    MLN_COMPARE_OP_EQUAL = 2,
    MLN_COMPARE_OP_LESS_OR_EQUAL = 3,
    MLN_COMPARE_OP_GREATER = 4,
    MLN_COMPARE_OP_NOT_EQUAL = 5,
    MLN_COMPARE_OP_GREATER_OR_EQUAL = 6,
    MLN_COMPARE_OP_ALWAYS = 7,
    MLN_COMPARE_OP_MAX_ENUM = 0x7FFFFFFF
} MlnCompareOp;

typedef enum MlnBorderColor {
    MLN_BORDER_COLOR_FLOAT_TRANSPARENT_BLACK = 0,
    MLN_BORDER_COLOR_INT_TRANSPARENT_BLACK = 1,
    MLN_BORDER_COLOR_FLOAT_OPAQUE_BLACK = 2,
    MLN_BORDER_COLOR_INT_OPAQUE_BLACK = 3,
    MLN_BORDER_COLOR_FLOAT_OPAQUE_WHITE = 4,
    MLN_BORDER_COLOR_INT_OPAQUE_WHITE = 5,
    MLN_BORDER_COLOR_MAX_ENUM = 0x7FFFFFFF
} MlnBorderColor;

typedef enum MlnSamplerReductionMode {
    MLN_SAMPLER_REDUCTION_MODE_WEIGHTED_AVERAGE = 0,
    MLN_SAMPLER_REDUCTION_MODE_MIN = 1,
    MLN_SAMPLER_REDUCTION_MODE_MAX = 2,
    MLN_SAMPLER_REDUCTION_MODE_MAX_ENUM = 0x7FFFFFFF
} MlnSamplerReductionMode;

typedef enum MlnSamplerDescriptorFlagBits {
    MLN_SAMPLER_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnSamplerDescriptorFlagBits;

typedef enum MlnSamplerYcbcrConversionDescriptorFlagBits {
    MLN_SAMPLER_YCBCR_CONVERSION_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnSamplerYcbcrConversionDescriptorFlagBits;

typedef enum MlnImageAspectFlagBits {
    MLN_IMAGE_ASPECT_NONE = 0,
    MLN_IMAGE_ASPECT_COLOR_BIT = 0x00000001,
    MLN_IMAGE_ASPECT_DEPTH_BIT = 0x00000002,
    MLN_IMAGE_ASPECT_STENCIL_BIT = 0x00000004,
    MLN_IMAGE_ASPECT_METADATA_BIT = 0x00000008,
    MLN_IMAGE_ASPECT_PLANE_0_BIT = 0x00000010,
    MLN_IMAGE_ASPECT_PLANE_1_BIT = 0x00000020,
    MLN_IMAGE_ASPECT_PLANE_2_BIT = 0x00000040,
    MLN_IMAGE_ASPECT_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnImageAspectFlagBits;

typedef enum MlnComponentSwizzle {
    MLN_COMPONENT_SWIZZLE_IDENTITY = 0,
    MLN_COMPONENT_SWIZZLE_ZERO = 1,
    MLN_COMPONENT_SWIZZLE_ONE = 2,
    MLN_COMPONENT_SWIZZLE_R = 3,
    MLN_COMPONENT_SWIZZLE_G = 4,
    MLN_COMPONENT_SWIZZLE_B = 5,
    MLN_COMPONENT_SWIZZLE_A = 6,
    MLN_COMPONENT_SWIZZLE_MAX_ENUM = 0x7FFFFFFF
} MlnComponentSwizzle;

typedef enum MlnBufferViewDescriptorFlagBits {
    MLN_BUFFER_VIEW_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnBufferViewDescriptorFlagBits;

typedef enum MlnImageViewDescriptorFlagBits {
    MLN_IMAGE_VIEW_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnImageViewDescriptorFlagBits;

typedef enum MlnImageViewType {
    MLN_IMAGE_VIEW_TYPE_1D = 0,
    MLN_IMAGE_VIEW_TYPE_2D = 1,
    MLN_IMAGE_VIEW_TYPE_3D = 2,
    MLN_IMAGE_VIEW_TYPE_CUBE = 3,
    MLN_IMAGE_VIEW_TYPE_1D_ARRAY = 4,
    MLN_IMAGE_VIEW_TYPE_2D_ARRAY = 5,
    MLN_IMAGE_VIEW_TYPE_CUBE_ARRAY = 6,
    MLN_IMAGE_VIEW_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnImageViewType;

typedef enum MlnShaderDescriptorFlagBits {
    MLN_SHADER_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnShaderDescriptorFlagBits;

typedef enum MlnShaderStageFlagBits {
    MLN_SHADER_STAGE_VERTEX_BIT = 0x00000001,
    MLN_SHADER_STAGE_FRAGMENT_BIT = 0x00000002,
    MLN_SHADER_STAGE_COMPUTE_BIT = 0x00000004,
    MLN_SHADER_STAGE_ALL_GRAPHICS = 0x00000003,
    MLN_SHADER_STAGE_ALL = 0x7FFFFFFF,
    MLN_SHADER_STAGE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnShaderStageFlagBits;

typedef enum MlnProgramInterfaceDescriptorFlagBits {
    MLN_PROGRAM_INTERFACE_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnProgramInterfaceDescriptorFlagBits;

typedef enum MlnProgramCacheHeaderVersion {
    MLN_PROGRAM_CACHE_HEADER_VERSION_ONE = 1,
    MLN_PROGRAM_CACHE_HEADER_VERSION_MAX_ENUM = 0x7FFFFFFF
} MlnProgramCacheHeaderVersion;

typedef enum MlnProgramCacheDescriptorFlagBits {
    MLN_PROGRAM_CACHE_CREATE_EXTERNALLY_SYNCHRONIZED_BIT = 0x00000001,
    MLN_PROGRAM_CACHE_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnProgramCacheDescriptorFlagBits;

typedef enum MlnProgramStageFlagBits {
    MLN_PROGRAM_STAGE_NONE = 0x00000001,
    MLN_PROGRAM_STAGE_DRAW_INDIRECT_BIT = 0x00000002,
    MLN_PROGRAM_STAGE_VERTEX_INPUT_BIT = 0x00000004,
    MLN_PROGRAM_STAGE_VERTEX_SHADER_BIT = 0x00000008,
    MLN_PROGRAM_STAGE_FRAGMENT_SHADER_BIT = 0x00000010,
    MLN_PROGRAM_STAGE_EARLY_FRAGMENT_TESTS_BIT = 0x00000020,
    MLN_PROGRAM_STAGE_LATE_FRAGMENT_TESTS_BIT = 0x00000040,
    MLN_PROGRAM_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT = 0x00000080,
    MLN_PROGRAM_STAGE_ALL_GRAPHICS_BIT = 0x00000100,
    MLN_PROGRAM_STAGE_COMPUTE_SHADER_BIT = 0x00000200,
    MLN_PROGRAM_STAGE_COPY_BIT = 0x00000400,
    MLN_PROGRAM_STAGE_RESOLVE_BIT = 0x00000800,
    MLN_PROGRAM_STAGE_BLIT_BIT = 0x00001000,
    MLN_PROGRAM_STAGE_CLEAR_BIT = 0x00002000,
    MLN_PROGRAM_STAGE_ALL_TRANSFER_BIT = 0x00004000,
    MLN_PROGRAM_STAGE_ALL_COMMANDS_BIT = 0x00008000,
    MLN_PROGRAM_STAGE_HOST_BIT = 0x00010000,
    MLN_PROGRAM_STAGE_INDEX_INPUT_BIT = 0x00020000,
    MLN_PROGRAM_STAGE_VERTEX_ATTRIBUTE_INPUT_BIT = 0x00040000,
    MLN_PROGRAM_STAGE_PRE_RASTERIZATION_SHADERS_BIT = 0x00080000,
    MLN_PROGRAM_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT = 0x00100000,
    MLN_PROGRAM_STAGE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnProgramStageFlagBits;

typedef enum MlnProgramStateFlagBits {
    MLN_PROGRAM_STATE_FAIL_ON_PIPELINE_COMPILE_REQUIRED_BIT = 0x00000001,
    MLN_PROGRAM_STATE_EARLY_RETURN_ON_FAILURE_BIT = 0x00000002,
    MLN_PROGRAM_STATE_NO_PROTECTED_ACCESS_BIT = 0x00000004,
    MLN_PROGRAM_STATE_PROTECTED_ACCESS_ONLY_BIT = 0x00000008,
    MLN_PROGRAM_STATE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT = 0x00000010,
    MLN_PROGRAM_STATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnProgramStateFlagBits;

typedef enum MlnShaderStageStateFlagBits {
    MLN_SHADER_STAGE_STATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnShaderStageStateFlagBits;

typedef enum MlnInputAssemblyStateFlagBits {
    MLN_INPUT_ASSEMBLY_STATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnInputAssemblyStateFlagBits;

typedef enum MlnVertexInputStateFlagBits {
    MLN_VERTEX_INPUT_STATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnVertexInputStateFlagBits;

typedef enum MlnViewportStateFlagBits {
    MLN_VIEWPORT_STATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnViewportStateFlagBits;

typedef enum MlnRasterizationStateFlagBits {
    MLN_RASTERIZATION_STATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnRasterizationStateFlagBits;

typedef enum MlnMultisampleStateFlagBits {
    MLN_MULTISAMPLE_STATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnMultisampleStateFlagBits;

typedef enum MlnDepthStencilStateFlagBits {
    MLN_DEPTH_STENCIL_STATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnDepthStencilStateFlagBits;

typedef enum MlnColorBlendStateFlagBits {
    MLN_COLOR_BLEND_STATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnColorBlendStateFlagBits;

typedef enum MlnDynamicStateFlagBits {
    MLN_DYNAMIC_STATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnDynamicStateFlagBits;

typedef enum MlnCreationFeedbackFlagBits {
    MLN_CREATION_FEEDBACK_VALID_BIT = 0x00000001,
    MLN_CREATION_FEEDBACK_APPLICATION_PIPELINE_CACHE_HIT_BIT = 0x00000002,
    MLN_CREATION_FEEDBACK_BASE_PIPELINE_ACCELERATION_BIT = 0x00000004,
    MLN_CREATION_FEEDBACK_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnCreationFeedbackFlagBits;

typedef enum MlnDynamicStateType {
    MLN_DYNAMIC_STATE_TYPE_VIEWPORT = 0,
    MLN_DYNAMIC_STATE_TYPE_SCISSOR = 1,
    MLN_DYNAMIC_STATE_TYPE_LINE_WIDTH = 2,
    MLN_DYNAMIC_STATE_TYPE_DEPTH_BIAS = 3,
    MLN_DYNAMIC_STATE_TYPE_BLEND_CONSTANTS = 4,
    MLN_DYNAMIC_STATE_TYPE_DEPTH_BOUNDS = 5,
    MLN_DYNAMIC_STATE_TYPE_STENCIL_COMPARE_MASK = 6,
    MLN_DYNAMIC_STATE_TYPE_STENCIL_WRITE_MASK = 7,
    MLN_DYNAMIC_STATE_TYPE_STENCIL_REFERENCE = 8,
    MLN_DYNAMIC_STATE_TYPE_PRIMITIVE_TOPOLOGY = 9,
    MLN_DYNAMIC_STATE_TYPE_PRIMITIVE_RESTART_ENABLE = 10,
    MLN_DYNAMIC_STATE_TYPE_RASTERIZER_DISCARD_ENABLE = 11,
    MLN_DYNAMIC_STATE_TYPE_CULL_MODE = 12,
    MLN_DYNAMIC_STATE_TYPE_FRONT_FACE = 13,
    MLN_DYNAMIC_STATE_TYPE_DEPTH_BIAS_ENABLE = 14,
    MLN_DYNAMIC_STATE_TYPE_SAMPLE_LOCATIONS = 15,
    MLN_DYNAMIC_STATE_TYPE_DEPTH_TEST_ENABLE = 16,
    MLN_DYNAMIC_STATE_TYPE_DEPTH_WRITE_ENABLE = 17,
    MLN_DYNAMIC_STATE_TYPE_DEPTH_COMPARE_OP = 18,
    MLN_DYNAMIC_STATE_TYPE_DEPTH_BOUNDS_TEST_ENABLE = 19,
    MLN_DYNAMIC_STATE_TYPE_STENCIL_TEST_ENABLE = 20,
    MLN_DYNAMIC_STATE_TYPE_STENCIL_OP = 21,
    MLN_DYNAMIC_STATE_TYPE_VIEWPORT_WITH_COUNT = 22,
    MLN_DYNAMIC_STATE_TYPE_SCISSOR_WITH_COUNT = 23,
    MLN_DYNAMIC_STATE_TYPE_VERTEX_INPUT_BINDING_STRIDE = 24,
    MLN_DYNAMIC_STATE_TYPE_FRAGMENT_SHADING_RATE = 25,
    MLN_DYNAMIC_STATE_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnDynamicStateType;

typedef enum MlnVertexInputRate {
    MLN_VERTEX_INPUT_RATE_VERTEX = 0,
    MLN_VERTEX_INPUT_RATE_INSTANCE = 1,
    MLN_VERTEX_INPUT_RATE_MAX_ENUM = 0x7FFFFFFF
} MlnVertexInputRate;

typedef enum MlnPrimitiveTopology {
    MLN_PRIMITIVE_TOPOLOGY_POINT_LIST = 0,
    MLN_PRIMITIVE_TOPOLOGY_LINE_LIST = 1,
    MLN_PRIMITIVE_TOPOLOGY_LINE_STRIP = 2,
    MLN_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST = 3,
    MLN_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP = 4,
    MLN_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN = 5,
    MLN_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY = 6,
    MLN_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY = 7,
    MLN_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY = 8,
    MLN_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY = 9,
    MLN_PRIMITIVE_TOPOLOGY_PATCH_LIST = 10,
    MLN_PRIMITIVE_TOPOLOGY_MAX_ENUM = 0x7FFFFFFF
} MlnPrimitiveTopology;

typedef enum MlnPolygonMode {
    MLN_POLYGON_MODE_FILL = 0,
    MLN_POLYGON_MODE_LINE = 1,
    MLN_POLYGON_MODE_POINT = 2,
    MLN_POLYGON_MODE_MAX_ENUM = 0x7FFFFFFF
} MlnPolygonMode;

typedef enum MlnFrontFace {
    MLN_FRONT_FACE_COUNTER_CLOCKWISE = 0,
    MLN_FRONT_FACE_CLOCKWISE = 1,
    MLN_FRONT_FACE_MAX_ENUM = 0x7FFFFFFF
} MlnFrontFace;

typedef enum MlnBlendFactor {
    MLN_BLEND_FACTOR_ZERO = 0,
    MLN_BLEND_FACTOR_ONE = 1,
    MLN_BLEND_FACTOR_SRC_COLOR = 2,
    MLN_BLEND_FACTOR_ONE_MINUS_SRC_COLOR = 3,
    MLN_BLEND_FACTOR_DST_COLOR = 4,
    MLN_BLEND_FACTOR_ONE_MINUS_DST_COLOR = 5,
    MLN_BLEND_FACTOR_SRC_ALPHA = 6,
    MLN_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA = 7,
    MLN_BLEND_FACTOR_DST_ALPHA = 8,
    MLN_BLEND_FACTOR_ONE_MINUS_DST_ALPHA = 9,
    MLN_BLEND_FACTOR_CONSTANT_COLOR = 10,
    MLN_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR = 11,
    MLN_BLEND_FACTOR_CONSTANT_ALPHA = 12,
    MLN_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA = 13,
    MLN_BLEND_FACTOR_SRC_ALPHA_SATURATE = 14,
    MLN_BLEND_FACTOR_SRC1_COLOR = 15,
    MLN_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR = 16,
    MLN_BLEND_FACTOR_SRC1_ALPHA = 17,
    MLN_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA = 18,
    MLN_BLEND_FACTOR_MAX_ENUM = 0x7FFFFFFF
} MlnBlendFactor;

typedef enum MlnStencilOp {
    MLN_STENCIL_OP_KEEP = 0,
    MLN_STENCIL_OP_ZERO = 1,
    MLN_STENCIL_OP_REPLACE = 2,
    MLN_STENCIL_OP_INCREMENT_AND_CLAMP = 3,
    MLN_STENCIL_OP_DECREMENT_AND_CLAMP = 4,
    MLN_STENCIL_OP_INVERT = 5,
    MLN_STENCIL_OP_INCREMENT_AND_WRAP = 6,
    MLN_STENCIL_OP_DECREMENT_AND_WRAP = 7,
    MLN_STENCIL_OP_MAX_ENUM = 0x7FFFFFFF
} MlnStencilOp;

typedef enum MlnLogicOp {
    MLN_LOGIC_OP_CLEAR = 0,
    MLN_LOGIC_OP_AND = 1,
    MLN_LOGIC_OP_AND_REVERSE = 2,
    MLN_LOGIC_OP_COPY = 3,
    MLN_LOGIC_OP_AND_INVERTED = 4,
    MLN_LOGIC_OP_NO_OP = 5,
    MLN_LOGIC_OP_XOR = 6,
    MLN_LOGIC_OP_OR = 7,
    MLN_LOGIC_OP_NOR = 8,
    MLN_LOGIC_OP_EQUIVALENT = 9,
    MLN_LOGIC_OP_INVERT = 10,
    MLN_LOGIC_OP_OR_REVERSE = 11,
    MLN_LOGIC_OP_COPY_INVERTED = 12,
    MLN_LOGIC_OP_OR_INVERTED = 13,
    MLN_LOGIC_OP_NAND = 14,
    MLN_LOGIC_OP_SET = 15,
    MLN_LOGIC_OP_MAX_ENUM = 0x7FFFFFFF
} MlnLogicOp;

typedef enum MlnBlendOp {
    MLN_BLEND_OP_ADD = 0,
    MLN_BLEND_OP_SUBTRACT = 1,
    MLN_BLEND_OP_REVERSE_SUBTRACT = 2,
    MLN_BLEND_OP_MIN = 3,
    MLN_BLEND_OP_MAX = 4,
    MLN_BLEND_OP_MAX_ENUM = 0x7FFFFFFF
} MlnBlendOp;

typedef enum MlnCullModeFlagBits {
    MLN_CULL_MODE_NONE_BIT = 0,
    MLN_CULL_MODE_FRONT_BIT = 0x00000001,
    MLN_CULL_MODE_BACK_BIT = 0x00000002,
    MLN_CULL_MODE_FRONT_AND_BACK_BIT = 0x00000003,
    MLN_CULL_MODE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnCullModeFlagBits;

typedef enum MlnStencilFaceFlagBits {
    MLN_STENCIL_FACE_FRONT_BIT = 0x00000001,
    MLN_STENCIL_FACE_BACK_BIT = 0x00000002,
    MLN_STENCIL_FACE_FRONT_AND_BACK = 0x00000003,
    MLN_STENCIL_FACE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnStencilFaceFlagBits;

typedef enum MlnColorComponentFlagBits {
    MLN_COLOR_COMPONENT_R_BIT = 0x00000001,
    MLN_COLOR_COMPONENT_G_BIT = 0x00000002,
    MLN_COLOR_COMPONENT_B_BIT = 0x00000004,
    MLN_COLOR_COMPONENT_A_BIT = 0x00000008,
    MLN_COLOR_COMPONENT_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnColorComponentFlagBits;

typedef enum MlnPriority {
    MLN_PRIORITY_LOW = 0,
    MLN_PRIORITY_MEDIUM = 1,
    MLN_PRIORITY_HIGH = 2,
    MLN_PRIORITY_MAX_ENUM = 0x7FFFFFFF
} MlnPriority;

typedef enum MlnLineRasterizationMode {
    MLN_LINE_RASTERIZATION_DEFAULT = 0,
    MLN_LINE_RASTERIZATION_RECTANGULAR = 1,
    MLN_LINE_RASTERIZATION_BRESENHAM = 2,
    MLN_LINE_RASTERIZATION_RECTANGULAR_SMOOTH = 3,
    MLN_LINE_RASTERIZATION_MODE_MAX_ENUM = 0x7FFFFFFF
} MlnLineRasterizationMode;

typedef enum MlnProvokingVertexMode {
    MLN_PROVOKING_VERTEX_FIRST = 0,
    MLN_PROVOKING_VERTEX_LAST = 1,
    MLN_PROVOKING_VERTEX_MODE_MAX_ENUM = 0x7FFFFFFF
} MlnProvokingVertexMode;

typedef enum MlnDepthBiasRepresentationMode {
    MLN_DEPTH_BIAS_REPRESENTATION_LEAST_REPRESENTABLE_VALUE_FORMAT = 0,
    MLN_DEPTH_BIAS_REPRESENTATION_LEAST_REPRESENTABLE_VALUE_FORCE_UNORM = 1,
    MLN_DEPTH_BIAS_REPRESENTATION_FLOAT = 2,
    MLN_DEPTH_BIAS_REPRESENTATION_MODE_MAX_ENUM = 0x7FFFFFFF
} MlnDepthBiasRepresentationMode;

typedef enum MlnAccessFlagBits {
    MLN_ACCESS_NONE = 0,
    MLN_ACCESS_INDIRECT_COMMAND_READ_BIT = 0x00000001,
    MLN_ACCESS_INDEX_READ_BIT = 0x00000002,
    MLN_ACCESS_VERTEX_ATTRIBUTE_READ_BIT = 0x00000004,
    MLN_ACCESS_UNIFORM_READ_BIT = 0x00000008,
    MLN_ACCESS_INPUT_ATTACHMENT_READ_BIT = 0x00000010,
    MLN_ACCESS_SHADER_READ_BIT = 0x00000020,
    MLN_ACCESS_SHADER_WRITE_BIT = 0x00000040,
    MLN_ACCESS_COLOR_ATTACHMENT_READ_BIT = 0x00000080,
    MLN_ACCESS_COLOR_ATTACHMENT_WRITE_BIT = 0x00000100,
    MLN_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT = 0x00000200,
    MLN_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT = 0x00000400,
    MLN_ACCESS_TRANSFER_READ_BIT = 0x00000800,
    MLN_ACCESS_TRANSFER_WRITE_BIT = 0x00001000,
    MLN_ACCESS_MEMORY_READ_BIT = 0x00002000,
    MLN_ACCESS_MEMORY_WRITE_BIT = 0x00004000,
    MLN_ACCESS_SHADER_SAMPLED_READ_BIT = 0x00008000,
    MLN_ACCESS_SHADER_STORAGE_READ_BIT = 0x00010000,
    MLN_ACCESS_SHADER_STORAGE_WRITE_BIT = 0x00020000,
    MLN_ACCESS_CONDITIONAL_RENDERING_READ_BIT = 0x00040000,
    MLN_ACCESS_FRAGMENT_SHADING_RATE_ATTACHMENT_READ_BIT = 0x00080000,
    MLN_ACCESS_SHADING_RATE_IMAGE_READ_BIT = 0x00100000,
    MLN_ACCESS_ACCELERATION_STRUCTURE_READ_BIT = 0x00200000,
    MLN_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT = 0x00400000,
    MLN_ACCESS_MICROMAP_READ_BIT = 0x00800000,
    MLN_ACCESS_MICROMAP_WRITE_BIT = 0x01000000,
    MLN_ACCESS_OPTICAL_FLOW_READ_BIT = 0x02000000,
    MLN_ACCESS_OPTICAL_FLOW_WRITE_BIT = 0x04000000,
    MLN_ACCESS_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnAccessFlagBits;

typedef enum MlnBindingType {
    MLN_BINDING_TYPE_SAMPLER = 0,
    MLN_BINDING_TYPE_COMBINED_IMAGE_SAMPLER = 1,
    MLN_BINDING_TYPE_SAMPLED_IMAGE = 2,
    MLN_BINDING_TYPE_STORAGE_IMAGE = 3,
    MLN_BINDING_TYPE_UNIFORM_TEXEL_BUFFER = 4,
    MLN_BINDING_TYPE_STORAGE_TEXEL_BUFFER = 5,
    MLN_BINDING_TYPE_UNIFORM_BUFFER = 6,
    MLN_BINDING_TYPE_STORAGE_BUFFER = 7,
    MLN_BINDING_TYPE_UNIFORM_BUFFER_DYNAMIC = 8,
    MLN_BINDING_TYPE_STORAGE_BUFFER_DYNAMIC = 9,
    MLN_BINDING_TYPE_INPUT_ATTACHMENT = 10,
    MLN_BINDING_TYPE_INLINE_UNIFORM_BLOCK = 11,
    MLN_BINDING_TYPE_ACCELERATION_STRUCTURE = 12,
    MLN_BINDING_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnBindingType;

typedef enum MlnBindingLayoutDescriptorFlagBits {
    MLN_BINDING_LAYOUT_DESCRIPTOR_UPDATE_AFTER_BIND_POOL_BIT = 0x00000001,
    MLN_BINDING_LAYOUT_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnBindingLayoutDescriptorFlagBits;

typedef enum MlnBindingSlotFlagBits {
    MLN_BINDING_SLOT_UPDATE_AFTER_BIND_BIT = 0x00000001,
    MLN_BINDING_SLOT_UPDATE_UNUSED_WHILE_PENDING_BIT = 0x00000002,
    MLN_BINDING_SLOT_PARTIALLY_BOUND_BIT = 0x00000004,
    MLN_BINDING_SLOT_VARIABLE_DESCRIPTOR_COUNT_BIT = 0x00000008,
    MLN_BINDING_SLOT_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnBindingSlotFlagBits;

typedef enum MlnSamplerYcbcrModelConversion {
    MLN_SAMPLER_YCBCR_MODEL_CONVERSION_RGB_IDENTITY = 0,
    MLN_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_IDENTITY = 1,
    MLN_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_709 = 2,
    MLN_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_601 = 3,
    MLN_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_2020 = 4,
    MLN_SAMPLER_YCBCR_MODEL_CONVERSION_MAX_ENUM = 0x7FFFFFFF
} MlnSamplerYcbcrModelConversion;

typedef enum MlnSamplerYcbcrRange {
    MLN_SAMPLER_YCBCR_RANGE_ITU_FULL = 0,
    MLN_SAMPLER_YCBCR_RANGE_ITU_NARROW = 1,
    MLN_SAMPLER_YCBCR_RANGE_MAX_ENUM = 0x7FFFFFFF
} MlnSamplerYcbcrRange;

typedef enum MlnChromaLocation {
    MLN_CHROMA_LOCATION_COSITED_EVEN = 0,
    MLN_CHROMA_LOCATION_MIDPOINT = 1,
    MLN_CHROMA_LOCATION_MAX_ENUM = 0x7FFFFFFF
} MlnChromaLocation;

typedef enum MlnGraphicsObjectGroupDescriptorFlagBits {
    MLN_GRAPHICS_OBJECT_GROUP_DESCRIPTOR_PERSISTENT_BIT = 0x00000001,
    MLN_GRAPHICS_OBJECT_GROUP_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnGraphicsObjectGroupDescriptorFlagBits;

typedef enum MlnComputeObjectGroupDescriptorFlagBits {
    MLN_COMPUTE_OBJECT_GROUP_DESCRIPTOR_PERSISTENT_BIT = 0x00000001,
    MLN_COMPUTE_OBJECT_GROUP_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnComputeObjectGroupDescriptorFlagBits;

typedef enum MlnTransferObjectGroupDescriptorFlagBits {
    MLN_TRANSFER_OBJECT_GROUP_DESCRIPTOR_PERSISTENT_BIT = 0x00000001,
    MLN_TRANSFER_OBJECT_GROUP_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnTransferObjectGroupDescriptorFlagBits;

typedef enum MlnClearObjectGroupDescriptorFlagBits {
    MLN_CLEAR_OBJECT_GROUP_DESCRIPTOR_PERSISTENT_BIT = 0x00000001,
    MLN_CLEAR_OBJECT_GROUP_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnClearObjectGroupDescriptorFlagBits;

typedef enum MlnBarrierObjectGroupDescriptorFlagBits {
    MLN_BARRIER_OBJECT_GROUP_DESCRIPTOR_BY_REGION_BIT = 0x00000001,
    MLN_BARRIER_OBJECT_GROUP_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnBarrierObjectGroupDescriptorFlagBits;

typedef enum MlnRenderingStateFlagBits {
    MLN_RENDERING_STATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnRenderingStateFlagBits;

typedef enum MlnResourceSetDescriptorFlagBits {
    MLN_RESOURCE_SET_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnResourceSetDescriptorFlagBits;

typedef enum MlnStateSetDescriptorFlagBits {
    MLN_STATE_SET_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnStateSetDescriptorFlagBits;

typedef enum MlnGraphicsCommandDescriptorFlagBits {
    MLN_GRAPHICS_COMMAND_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnGraphicsCommandDescriptorFlagBits;

typedef enum MlnComputeCommandDescriptorFlagBits {
    MLN_COMPUTE_COMMAND_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnComputeCommandDescriptorFlagBits;

typedef enum MlnGraphicsObjectGroupUpdateDescriptorFlagBits {
    MLN_GRAPHICS_OBJECT_GROUP_UPDATE_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnGraphicsObjectGroupUpdateDescriptorFlagBits;

typedef enum MlnComputeObjectGroupUpdateDescriptorFlagBits {
    MLN_COMPUTE_OBJECT_GROUP_UPDATE_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnComputeObjectGroupUpdateDescriptorFlagBits;

typedef enum MlnIndexType {
    MLN_INDEX_TYPE_NONE = 0,
    MLN_INDEX_TYPE_UINT8 = 1,
    MLN_INDEX_TYPE_UINT16 = 2,
    MLN_INDEX_TYPE_UINT32 = 3,
    MLN_INDEX_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnIndexType;

typedef enum MlnDynamicResourceType {
    MLN_DYNAMIC_RESOURCE_TYPE_BINDING_SETS = 0,
    MLN_DYNAMIC_RESOURCE_TYPE_PROGRAM_CONSTANTS = 1,
    MLN_DYNAMIC_RESOURCE_TYPE_VERTEX_BUFFERS = 2,
    MLN_DYNAMIC_RESOURCE_TYPE_INDEX_BUFFERS = 3,
    MLN_DYNAMIC_RESOURCE_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnDynamicResourceType;

typedef enum MlnGraphicsCommandType {
    MLN_GRAPHICS_COMMAND_TYPE_DRAW = 0,
    MLN_GRAPHICS_COMMAND_TYPE_DRAW_INDEXED = 1,
    MLN_GRAPHICS_COMMAND_TYPE_DRAW_INDIRECT = 2,
    MLN_GRAPHICS_COMMAND_TYPE_DRAW_INDEXED_INDIRECT = 3,
    MLN_GRAPHICS_COMMAND_TYPE_DRAW_INDIRECT_COUNT = 4,
    MLN_GRAPHICS_COMMAND_TYPE_DRAW_INDEXED_INDIRECT_COUNT = 5,
    MLN_GRAPHICS_COMMAND_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnGraphicsCommandType;

typedef enum MlnComputeCommandType {
    MLN_COMPUTE_COMMAND_TYPE_GROUP_COUNT = 0,
    MLN_COMPUTE_COMMAND_TYPE_GROUP_COUNT_INDIRECT = 1,
    MLN_COMPUTE_COMMAND_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnComputeCommandType;

typedef enum MlnGraphicsObjectGroupModifierType {
    MLN_GRAPHICS_OBJECT_GROUP_MODIFIER_TYPE_BINDING_SETS = 0,
    MLN_GRAPHICS_OBJECT_GROUP_MODIFIER_TYPE_PROGRAM_CONSTANTS = 1,
    MLN_GRAPHICS_OBJECT_GROUP_MODIFIER_TYPE_VERTEX_BUFFERS = 2,
    MLN_GRAPHICS_OBJECT_GROUP_MODIFIER_TYPE_INDEX_BUFFER = 3,
    MLN_GRAPHICS_OBJECT_GROUP_MODIFIER_TYPE_COMMAND = 4,
    MLN_GRAPHICS_OBJECT_GROUP_MODIFIER_TYPE_VIEWPORT = 5,
    MLN_GRAPHICS_OBJECT_GROUP_MODIFIER_TYPE_SCISSOR = 6,
    MLN_GRAPHICS_OBJECT_GROUP_MODIFIER_TYPE_LINE_WIDTH = 7,
    MLN_GRAPHICS_OBJECT_GROUP_MODIFIER_TYPE_DEPTH_BIAS = 8,
    MLN_GRAPHICS_OBJECT_GROUP_MODIFIER_TYPE_BLEND_CONSTANTS = 9,
    MLN_GRAPHICS_OBJECT_GROUP_MODIFIER_TYPE_DEPTH_BOUNDS = 10,
    MLN_GRAPHICS_OBJECT_GROUP_MODIFIER_TYPE_STENCIL_COMPARE_MASK = 11,
    MLN_GRAPHICS_OBJECT_GROUP_MODIFIER_TYPE_STENCIL_WRITE_MASK = 12,
    MLN_GRAPHICS_OBJECT_GROUP_MODIFIER_TYPE_STENCIL_REFERENCE = 13,
    MLN_GRAPHICS_OBJECT_GROUP_MODIFIER_TYPE_BINDING_SETS_DYNAMIC_OFFSETS = 14,
    MLN_GRAPHICS_OBJECT_GROUP_MODIFIER_TYPE_SAMPLE_LOCATION = 15,
    MLN_GRAPHICS_OBJECT_GROUP_MODIFIER_TYPE_VIEWPORT_WITH_COUNT = 16,
    MLN_GRAPHICS_OBJECT_GROUP_MODIFIER_TYPE_SCISSOR_WITH_COUNT = 17,
    MLN_GRAPHICS_OBJECT_GROUP_MODIFIER_TYPE_FRAGMENT_SHADING_RATE = 18,
    MLN_GRAPHICS_OBJECT_GROUP_MODIFIER_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnGraphicsObjectGroupModifierType;

typedef enum MlnComputeObjectGroupModifierType {
    MLN_COMPUTE_OBJECT_GROUP_MODIFIER_TYPE_BINDING_SETS = 0,
    MLN_COMPUTE_OBJECT_GROUP_MODIFIER_TYPE_PROGRAM_CONSTANTS = 1,
    MLN_COMPUTE_OBJECT_GROUP_MODIFIER_TYPE_BASEGROUP = 2,
    MLN_COMPUTE_OBJECT_GROUP_MODIFIER_TYPE_GROUPCOUNT = 3,
    MLN_COMPUTE_OBJECT_GROUP_MODIFIER_TYPE_GROUPCOUNT_INDIRECT = 4,
    MLN_COMPUTE_OBJECT_GROUP_MODIFIER_TYPE_BINDING_SETS_DYNAMIC_OFFSETS = 5,
    MLN_COMPUTE_OBJECT_GROUP_MODIFIER_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnComputeObjectGroupModifierType;

typedef enum MlnTransferCommandType {
    MLN_TRANSFER_COMMAND_TYPE_COPY_BUFFER = 0,
    MLN_TRANSFER_COMMAND_TYPE_COPY_IMAGE = 1,
    MLN_TRANSFER_COMMAND_TYPE_COPY_BUFFER_TO_IMAGE = 2,
    MLN_TRANSFER_COMMAND_TYPE_COPY_IMAGE_TO_BUFFER = 3,
    MLN_TRANSFER_COMMAND_TYPE_BLIT_IMAGE = 4,
    MLN_TRANSFER_COMMAND_TYPE_RESOLVE_IMAGE = 5,
    MLN_TRANSFER_COMMAND_TYPE_GENERATE_MIPMAP = 6,
    MLN_TRANSFER_COMMAND_TYPE_CLEAR_IMAGE = 7,
    MLN_TRANSFER_COMMAND_TYPE_FILL_BUFFER = 8,
    MLN_TRANSFER_COMMAND_TYPE_UPDATE_BUFFER = 9,
    MLN_TRANSFER_COMMAND_TYPE_COPY_QUERY_POOL_RESULT = 10,
    MLN_TRANSFER_COMMAND_TYPE_RESET_QUERY_POOL = 11,
    MLN_TRANSFER_COMMAND_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnTransferCommandType;

typedef enum MlnConditionalRenderingFlagBits {
    MLN_CONDITIONAL_RENDERING_INVERTED_BIT = 0x00000001,
    MLN_CONDITIONAL_RENDERING_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnConditionalRenderingFlagBits;

typedef enum MlnGraphicsDataGraphDescriptorFlagBits {
    MLN_GRAPHICS_DATA_GRAPH_DESCRIPTOR_PERSISTENT_BIT = 0x00000001,
    MLN_GRAPHICS_DATA_GRAPH_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnGraphicsDataGraphDescriptorFlagBits;

typedef enum MlnComputeDataGraphDescriptorFlagBits {
    MLN_COMPUTE_DATA_GRAPH_DESCRIPTOR_PERSISTENT_BIT = 0x00000001,
    MLN_COMPUTE_DATA_GRAPH_DESCRIPTOR_SEQUENTIAL_BIT = 0x00000002,
    MLN_COMPUTE_DATA_GRAPH_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnComputeDataGraphDescriptorFlagBits;

typedef enum MlnTransferDataGraphDescriptorFlagBits {
    MLN_TRANSFER_DATA_GRAPH_DESCRIPTOR_PERSISTENT_BIT = 0x00000001,
    MLN_TRANSFER_DATA_GRAPH_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnTransferDataGraphDescriptorFlagBits;

typedef enum MlnDataGraphSubmitDescriptorFlagBits {
    MLN_DATA_GRAPH_SUBMIT_DESCRIPTOR_SUSPEND_BIT = 0x00000001,
    MLN_DATA_GRAPH_SUBMIT_DESCRIPTOR_RESUME_BIT = 0x00000002,
    MLN_DATA_GRAPH_SUBMIT_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnDataGraphSubmitDescriptorFlagBits;

typedef enum MlnPassNodeResourceType {
    MLN_PASS_NODE_RESOURCE_TYPE_IMAGE = 0,
    MLN_PASS_NODE_RESOURCE_TYPE_BUFFER = 1,
    MLN_PASS_NODE_RESOURCE_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnPassNodeResourceType;

typedef enum MlnPassNodeHintType {
    MLN_PASS_NODE_HINT_TYPE_NONE = 0,
    MLN_PASS_NODE_HINT_TYPE_SKINNING = 1,
    MLN_PASS_NODE_HINT_TYPE_CLOTH_SIMULATION = 2,
    MLN_PASS_NODE_HINT_TYPE_PARTICLE_SIMULATION = 3,
    MLN_PASS_NODE_HINT_TYPE_SKY_ATMOSPHERE_LUT = 4,
    MLN_PASS_NODE_HINT_TYPE_COLOR_GRADING_LUT = 5,
    MLN_PASS_NODE_HINT_TYPE_VIRTUAL_TEXTURE = 6,
    MLN_PASS_NODE_HINT_TYPE_DEPTH_PRE_PASS = 7,
    MLN_PASS_NODE_HINT_TYPE_RENDER_HZB = 8,
    MLN_PASS_NODE_HINT_TYPE_HZB_CULLING = 9,
    MLN_PASS_NODE_HINT_TYPE_LIGHT_CULLING = 10,
    MLN_PASS_NODE_HINT_TYPE_RENDER_VELOCITIES = 11,
    MLN_PASS_NODE_HINT_TYPE_DUAL_PARABOLOID_SPHERE_MAP = 12,
    MLN_PASS_NODE_HINT_TYPE_SHADOW_DEPTH = 13,
    MLN_PASS_NODE_HINT_TYPE_VSM = 14,
    MLN_PASS_NODE_HINT_TYPE_BASE_PASS = 15,
    MLN_PASS_NODE_HINT_TYPE_DECALS = 16,
    MLN_PASS_NODE_HINT_TYPE_VOLUMETRIC_CLOUDS = 17,
    MLN_PASS_NODE_HINT_TYPE_SS_SHADOW = 18,
    MLN_PASS_NODE_HINT_TYPE_PLANAR_REFLECTION = 19,
    MLN_PASS_NODE_HINT_TYPE_DEFERRED_SHADING = 20,
    MLN_PASS_NODE_HINT_TYPE_HBAO = 21,
    MLN_PASS_NODE_HINT_TYPE_GTAO = 22,
    MLN_PASS_NODE_HINT_TYPE_SSAO = 23,
    MLN_PASS_NODE_HINT_TYPE_RTAO = 24,
    MLN_PASS_NODE_HINT_TYPE_VOLUMETRIC_LIGHT = 25,
    MLN_PASS_NODE_HINT_TYPE_FOG = 26,
    MLN_PASS_NODE_HINT_TYPE_CLOUD = 27,
    MLN_PASS_NODE_HINT_TYPE_TRANSLUCENCY = 28,
    MLN_PASS_NODE_HINT_TYPE_EYE_ADAPTATION = 29,
    MLN_PASS_NODE_HINT_TYPE_DISTORTION = 30,
    MLN_PASS_NODE_HINT_TYPE_DOF = 31,
    MLN_PASS_NODE_HINT_TYPE_BLOOM = 32,
    MLN_PASS_NODE_HINT_TYPE_LENS_FLARE = 33,
    MLN_PASS_NODE_HINT_TYPE_RADIAL_BLUR = 34,
    MLN_PASS_NODE_HINT_TYPE_DIRECTIONAL_BLUR = 35,
    MLN_PASS_NODE_HINT_TYPE_TAA = 36,
    MLN_PASS_NODE_HINT_TYPE_MSAA = 37,
    MLN_PASS_NODE_HINT_TYPE_SMAA = 38,
    MLN_PASS_NODE_HINT_TYPE_FXAA = 39,
    MLN_PASS_NODE_HINT_TYPE_MOTION_BLUR = 40,
    MLN_PASS_NODE_HINT_TYPE_FSR = 41,
    MLN_PASS_NODE_HINT_TYPE_SUN_MERGE = 42,
    MLN_PASS_NODE_HINT_TYPE_OUTLINE = 43,
    MLN_PASS_NODE_HINT_TYPE_COLOR_GRADING = 44,
    MLN_PASS_NODE_HINT_TYPE_UBER = 45,
    MLN_PASS_NODE_HINT_TYPE_TONEMAP = 46,
    MLN_PASS_NODE_HINT_TYPE_UI = 47,
    MLN_PASS_NODE_HINT_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnPassNodeHintType;

typedef enum MlnPassNodeWorkloadType {
    MLN_PASS_NODE_WORKLOAD_TYPE_NONE = 0,
    MLN_PASS_NODE_WORKLOAD_TYPE_DRAW_CNT = 1,
    MLN_PASS_NODE_WORKLOAD_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnPassNodeWorkloadType;

typedef enum MlnPassNodeDescriptorFlagBits {
    MLN_PASS_NODE_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnPassNodeDescriptorFlagBits;

typedef enum MlnSchedulingGraphDescriptorFlagBits {
    MLN_SCHEDULING_GRAPH_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnSchedulingGraphDescriptorFlagBits;

typedef enum MlnSchedulingGraphSubmitDescriptorFlagBits {
    MLN_SCHEDULING_GRAPH_SUBMIT_DESCRIPTOR_SERIALIZED_BIT = 0x00000001,
    MLN_SCHEDULING_GRAPH_SUBMIT_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnSchedulingGraphSubmitDescriptorFlagBits;

typedef enum MlnTimelineType {
    MLN_TIMELINE_TYPE_BINARY = 0,
    MLN_TIMELINE_TYPE_COUNTER = 1,
    MLN_TIMELINE_TYPE_HTS = 2,
    MLN_TIMELINE_TYPE_FFTS = 3,
    MLN_TIMELINE_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnTimelineType;

typedef enum MlnTimelineWaitFlagBits {
    MLN_TIMELINE_WAIT_ANY_BIT = 0x00000001,
    MLN_TIMELINE_WAIT_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnTimelineWaitFlagBits;

typedef enum MlnTimelineSignalFlagBits {
    MLN_TIMELINE_SIGNAL_ANY_BIT = 0x00000001,
    MLN_TIMELINE_SIGNAL_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnTimelineSignalFlagBits;

typedef enum MlnTimelineExportFlagBits {
    MLN_TIMELINE_EXPORT_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnTimelineExportFlagBits;

typedef enum MlnTimelineImportFlagBits {
    MLN_TIMELINE_IMPORT_TEMPORARY_BIT = 0x00000001,
    MLN_TIMELINE_IMPORT_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnTimelineImportFlagBits;

typedef enum MlnTimelineDescriptorFlagBits {
    MLN_TIMELINE_DESCRIPTOR_EXTERNAL_SYNC_FD_BIT = 0x00000001,
    MLN_TIMELINE_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnTimelineDescriptorFlagBits;

typedef enum MlnResolveModeFlagBits {
    MLN_RESOLVE_MODE_NONE = 0,
    MLN_RESOLVE_MODE_SAMPLE_ZERO_BIT = 0x00000001,
    MLN_RESOLVE_MODE_AVERAGE_BIT = 0x00000002,
    MLN_RESOLVE_MODE_MIN_BIT = 0x00000004,
    MLN_RESOLVE_MODE_MAX_BIT = 0x00000008,
    MLN_RESOLVE_MODE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnResolveModeFlagBits;

typedef enum MlnAttachmentLoadOp {
    MLN_ATTACHMENT_LOAD_OP_LOAD = 0,
    MLN_ATTACHMENT_LOAD_OP_CLEAR = 1,
    MLN_ATTACHMENT_LOAD_OP_DONT_CARE = 2,
    MLN_ATTACHMENT_LOAD_OP_NONE = 3,
    MLN_ATTACHMENT_LOAD_OP_MAX_ENUM = 0x7FFFFFFF
} MlnAttachmentLoadOp;

typedef enum MlnAttachmentStoreOp {
    MLN_ATTACHMENT_STORE_OP_STORE = 0,
    MLN_ATTACHMENT_STORE_OP_DONT_CARE = 1,
    MLN_ATTACHMENT_STORE_OP_NONE = 2,
    MLN_ATTACHMENT_STORE_OP_MAX_ENUM = 0x7FFFFFFF
} MlnAttachmentStoreOp;

typedef enum MlnRenderTargetDescriptorFlagBits {
    MLN_RENDER_TARGET_DESCRIPTOR_PERSISTENT_BIT = 0x00000001,
    MLN_RENDER_TARGET_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnRenderTargetDescriptorFlagBits;

typedef enum MlnPrivateDataSlotDescriptorFlagBits {
    MLN_PRIVATE_DATA_SLOT_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnPrivateDataSlotDescriptorFlagBits;

typedef enum MlnColorSpace {
    MLN_COLOR_SPACE_SRGB_NONLINEAR = 0,
    MLN_COLOR_SPACE_DISPLAY_P3_NONLINEAR = 1,
    MLN_COLOR_SPACE_EXTENDED_SRGB_LINEAR = 2,
    MLN_COLOR_SPACE_DISPLAY_P3_LINEAR = 3,
    MLN_COLOR_SPACE_DCI_P3_NONLINEAR = 4,
    MLN_COLOR_SPACE_BT709_LINEAR = 5,
    MLN_COLOR_SPACE_BT709_NONLINEAR = 6,
    MLN_COLOR_SPACE_BT2020_LINEAR = 7,
    MLN_COLOR_SPACE_HDR10_ST2084 = 8,
    MLN_COLOR_SPACE_HDR_VIVID = 9,
    MLN_COLOR_SPACE_HDR10_HLG = 10,
    MLN_COLOR_SPACE_ADOBERGB_LINEAR = 11,
    MLN_COLOR_SPACE_ADOBERGB_NONLINEAR = 12,
    MLN_COLOR_SPACE_PASS_THROUGH = 13,
    MLN_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR = 14,
    MLN_COLOR_SPACE_MAX_ENUM = 0x7FFFFFFF
} MlnColorSpace;

typedef enum MlnLossyTypes {
    MLN_LOSSY_TYPE_LOSSLESS = 0,
    MLN_LOSSY_TYPE_LOSSY_HALF = 1,
    MLN_LOSSY_TYPE_LOSSY_ONE_THIRD = 2,
    MLN_LOSSY_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnLossyTypes;

typedef enum MlnDisplaySurfaceTransformFlagBits {
    MLN_DISPLAY_SURFACE_TRANSFORM_IDENTITY_BIT = 0x00000001,
    MLN_DISPLAY_SURFACE_TRANSFORM_ROTATE_90_BIT = 0x00000002,
    MLN_DISPLAY_SURFACE_TRANSFORM_ROTATE_180_BIT = 0x00000004,
    MLN_DISPLAY_SURFACE_TRANSFORM_ROTATE_270_BIT = 0x00000008,
    MLN_DISPLAY_SURFACE_TRANSFORM_MIRROR_BIT = 0x00000010,
    MLN_DISPLAY_SURFACE_TRANSFORM_MIRROR_ROTATE_90_BIT = 0x00000020,
    MLN_DISPLAY_SURFACE_TRANSFORM_MIRROR_ROTATE_180_BIT = 0x00000040,
    MLN_DISPLAY_SURFACE_TRANSFORM_MIRROR_ROTATE_270_BIT = 0x00000080,
    MLN_DISPLAY_SURFACE_TRANSFORM_INHERIT_BIT = 0x00000100,
    MLN_DISPLAY_SURFACE_TRANSFORM_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnDisplaySurfaceTransformFlagBits;

typedef enum MlnSwapchainDescriptorFlagBits {
    MLN_SWAPCHAIN_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnSwapchainDescriptorFlagBits;

typedef enum MlnCompositeAlphaFlagBits {
    MLN_COMPOSITE_ALPHA_INHERIT_BIT = 0x00000001,
    MLN_COMPOSITE_ALPHA_OPAQUE_BIT = 0x00000002,
    MLN_COMPOSITE_ALPHA_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnCompositeAlphaFlagBits;

typedef enum MlnDisplayModeDescriptorFlagBits {
    MLN_DISPLAY_MODE_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnDisplayModeDescriptorFlagBits;

typedef enum MlnDisplaySurfaceDescriptorFlagBits {
    MLN_DISPLAY_SURFACE_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnDisplaySurfaceDescriptorFlagBits;

typedef enum MlnPresentMode {
    MLN_PRESENT_MODE_FIFO = 0,
    MLN_PRESENT_MODE_MAILBOX = 1,
    MLN_PRESENT_MODE_IMMEDIATE = 2,
    MLN_PRESENT_MODE_MAX_ENUM = 0x7FFFFFFF
} MlnPresentMode;

typedef enum MlnAccelerationStructureInstanceFlagBits {
    MLN_ACCELERATION_STRUCTURE_INSTANCE_TRIANGLE_FACING_CULL_DISABLE_BIT =
        0x00000001,
    MLN_ACCELERATION_STRUCTURE_INSTANCE_TRIANGLE_FLIP_FACING_BIT = 0x00000002,
    MLN_ACCELERATION_STRUCTURE_INSTANCE_FORCE_OPAQUE_BIT = 0x00000004,
    MLN_ACCELERATION_STRUCTURE_INSTANCE_FORCE_NO_OPAQUE_BIT = 0x00000008,
    MLN_ACCELERATION_STRUCTURE_INSTANCE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnAccelerationStructureInstanceFlagBits;

typedef enum MlnGeometryFlagBits {
    MLN_GEOMETRY_OPAQUE_BIT = 0x00000001,
    MLN_GEOMETRY_NO_DUPLICATE_ANY_HIT_INVOCATION_BIT = 0x00000002,
    MLN_GEOMETRY_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnGeometryFlagBits;

typedef enum MlnGeometryType {
    MLN_GEOMETRY_TYPE_TRIANGLES = 0,
    MLN_GEOMETRY_TYPE_AABBS = 1,
    MLN_GEOMETRY_TYPE_INSTANCES = 2,
    MLN_GEOMETRY_TYPE_ELLIPSOID = 3,
    MLN_GEOMETRY_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnGeometryType;

typedef enum MlnAccelerationStructureType {
    MLN_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL = 0,
    MLN_ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL = 1,
    MLN_ACCELERATION_STRUCTURE_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnAccelerationStructureType;

typedef enum MlnBuildAccelerationStructureFlagBits {
    MLN_BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT = 0x00000001,
    MLN_BUILD_ACCELERATION_STRUCTURE_ALLOW_COMPACTION_BIT = 0x00000002,
    MLN_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_TRACE_BIT = 0x00000004,
    MLN_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_BUILD_BIT = 0x00000008,
    MLN_BUILD_ACCELERATION_STRUCTURE_LOW_MEMORY_BIT = 0x00000010,
    MLN_BUILD_ACCELERATION_STRUCTURE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnBuildAccelerationStructureFlagBits;

typedef enum MlnAccelerationStructureBuildMode {
    MLN_ACCELERATION_STRUCTURE_BUILD_MODE_BUILD = 0,
    MLN_ACCELERATION_STRUCTURE_BUILD_MODE_UPDATE = 1,
    MLN_ACCELERATION_STRUCTURE_BUILD_MODE_MAX_ENUM = 0x7FFFFFFF
} MlnAccelerationStructureBuildMode;

typedef enum MlnAccelerationStructureCommandType {
    MLN_ACCELERATION_STRUCTURE_COMMAND_TYPE_BUILD = 0,
    MLN_ACCELERATION_STRUCTURE_COMMAND_TYPE_BUILD_INDIRECT = 1,
    MLN_ACCELERATION_STRUCTURE_COMMAND_TYPE_COPY = 2,
    MLN_ACCELERATION_STRUCTURE_COMMAND_TYPE_SERIALIZE = 3,
    MLN_ACCELERATION_STRUCTURE_COMMAND_TYPE_DESERIALIZE = 4,
    MLN_ACCELERATION_STRUCTURE_COMMAND_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnAccelerationStructureCommandType;

typedef enum MlnAccelerationStructureCopyMode {
    MLN_ACCELERATION_STRUCTURE_COPY_MODE_CLONE = 0,
    MLN_ACCELERATION_STRUCTURE_COPY_MODE_COMPACT = 1,
    MLN_ACCELERATION_STRUCTURE_COPY_MODE_MAX_ENUM = 0x7FFFFFFF
} MlnAccelerationStructureCopyMode;

typedef enum MlnAccelerationStructureDescriptorFlagBits {
    MLN_ACCELERATION_STRUCTURE_DESCRIPTOR_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT =
        0x00000001,
    MLN_ACCELERATION_STRUCTURE_DESCRIPTOR_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT =
        0x00000002,
    MLN_ACCELERATION_STRUCTURE_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnAccelerationStructureDescriptorFlagBits;

typedef enum MlnAccelerationStructureObjectGroupDescriptorFlagBits {
    MLN_ACCELERATION_STRUCTURE_OBJECT_GROUP_PERSISTENT_BIT = 0x00000001,
    MLN_ACCELERATION_STRUCTURE_OBJECT_GROUP_DESCRIPTOR_FLAG_BITS_MAX_ENUM =
        0x7FFFFFFF
} MlnAccelerationStructureObjectGroupDescriptorFlagBits;

typedef enum MlnAccelerationStructureDataGraphDescriptorFlagBits {
    MLN_ACCELERATION_STRUCTURE_DATA_GRAPH_PERSISTENT_BIT = 0x00000001,
    MLN_ACCELERATION_STRUCTURE_DATA_GRAPH_DESCRIPTOR_FLAG_BITS_MAX_ENUM =
        0x7FFFFFFF
} MlnAccelerationStructureDataGraphDescriptorFlagBits;

typedef enum MlnAccelerationStructureCompatibility {
    MLN_ACCELERATION_STRUCTURE_COMPATIBILITY_COMPATIBLE = 0,
    MLN_ACCELERATION_STRUCTURE_COMPATIBILITY_INCOMPATIBLE = 1,
    MLN_ACCELERATION_STRUCTURE_COMPATIBILITY_MAX_ENUM = 0x7FFFFFFF
} MlnAccelerationStructureCompatibility;

typedef enum MlnQueryType {
    MLN_QUERY_TYPE_OCCLUSION = 0,
    MLN_QUERY_TYPE_PRIMITIVES = 1,
    MLN_QUERY_TYPE_TIMESTAMP = 2,
    MLN_QUERY_TYPE_ACCELERATION_STRUCTURE = 3,
    MLN_QUERY_TYPE_PERFORMANCE = 4,
    MLN_QUERY_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnQueryType;

typedef enum MlnCounterSet {
    MLN_COUNTER_SET_OCCLUSION = 0,
    MLN_COUNTER_SET_BINARY_OCCLUSION = 1,
    MLN_COUNTER_SET_PRIMITIVES = 2,
    MLN_COUNTER_SET_TIMESTAMP = 3,
    MLN_COUNTER_SET_ACCELERATION_STRUCTURE = 4,
    MLN_COUNTER_SET_MAX_ENUM = 0x7FFFFFFF
} MlnCounterSet;

typedef enum MlnCounter {
    MLN_COUNTER_OCCLUSION = 0,
    MLN_COUNTER_BINARY_OCCLUSION = 1,
    MLN_COUNTER_PRIMITIVES_GENERATED = 2,
    MLN_COUNTER_TIMESTAMP = 3,
    MLN_COUNTER_ACCELERATION_STRUCTURE_SIZE = 4,
    MLN_COUNTER_ACCELERATION_STRUCTURE_COMPACTED_SIZE = 5,
    MLN_COUNTER_ACCELERATION_STRUCTURE_SERIALIZATION_SIZE = 6,
    MLN_COUNTER_ACCELERATION_STRUCTURE_SERIALIZATION_BOTTOM_LEVEL_POINTERS = 7,
    MLN_COUNTER_MAX_ENUM = 0x7FFFFFFF
} MlnCounter;

typedef enum MlnQueryCollectionType {
    MLN_QUERY_COLLECTION_TYPE_RANGE = 0,
    MLN_QUERY_COLLECTION_TYPE_POINT = 1,
    MLN_QUERY_COLLECTION_TYPE_SAMPLE = 2,
    MLN_QUERY_COLLECTION_TYPE_OBJECT_PROPERTY = 3,
    MLN_QUERY_COLLECTION_TYPE_MAX_ENUM = 0x7FFFFFFF
} MlnQueryCollectionType;

typedef enum MlnQuerySampleCollectionMode {
    MLN_QUERY_SAMPLE_COLLECTION_MODE_CLEAR = 0,
    MLN_QUERY_SAMPLE_COLLECTION_MODE_WRITE = 1,
    MLN_QUERY_SAMPLE_COLLECTION_MODE_MAX_ENUM = 0x7FFFFFFF
} MlnQuerySampleCollectionMode;

typedef enum MlnQuerySampleCollectionLocation {
    MLN_QUERY_SAMPLE_COLLECTION_LOCATION_DATAGRAPH_START = 0,
    MLN_QUERY_SAMPLE_COLLECTION_LOCATION_DATAGRAPH_END = 1,
    MLN_QUERY_SAMPLE_COLLECTION_LOCATION_BINNING_START = 2,
    MLN_QUERY_SAMPLE_COLLECTION_LOCATION_BINNING_END = 3,
    MLN_QUERY_SAMPLE_COLLECTION_LOCATION_RENDERING_START = 4,
    MLN_QUERY_SAMPLE_COLLECTION_LOCATION_RENDERING_END = 5,
    MLN_QUERY_SAMPLE_COLLECTION_LOCATION_MAX_ENUM = 0x7FFFFFFF
} MlnQuerySampleCollectionLocation;

typedef enum MlnCounterStorage {
    MLN_COUNTER_STORAGE_INT32 = 0,
    MLN_COUNTER_STORAGE_INT64 = 1,
    MLN_COUNTER_STORAGE_UINT32 = 2,
    MLN_COUNTER_STORAGE_UINT64 = 3,
    MLN_COUNTER_STORAGE_FLOAT32 = 4,
    MLN_COUNTER_STORAGE_FLOAT64 = 5,
    MLN_COUNTER_STORAGE_MAX_ENUM = 0x7FFFFFFF
} MlnCounterStorage;

typedef enum MlnCounterUnit {
    MLN_COUNTER_UNIT_GENERIC = 0,
    MLN_COUNTER_UNIT_CYCLES = 1,
    MLN_COUNTER_UNIT_MICROSECONDS = 2,
    MLN_COUNTER_UNIT_PERCENTAGE = 3,
    MLN_COUNTER_UNIT_MEGABYTES = 4,
    MLN_COUNTER_UNIT_MEGABYTES_PER_SECOND = 5,
    MLN_COUNTER_UNIT_VERTICES = 6,
    MLN_COUNTER_UNIT_PRIMITIVES = 7,
    MLN_COUNTER_UNIT_QUADS = 8,
    MLN_COUNTER_UNIT_TEXELS = 9,
    MLN_COUNTER_UNIT_INVOCATIONS = 10,
    MLN_COUNTER_UNIT_INSTRUCTIONS = 11,
    MLN_COUNTER_UNIT_WARPS = 12,
    MLN_COUNTER_UNIT_WARPS_PER_CYCLE = 13,
    MLN_COUNTER_UNIT_RAYS = 14,
    MLN_COUNTER_UNIT_TRIANGLES = 15,
    MLN_COUNTER_UNIT_NODES = 16,
    MLN_COUNTER_UNIT_WATTS = 17,
    MLN_COUNTER_UNIT_VOLTS = 18,
    MLN_COUNTER_UNIT_AMPS = 19,
    MLN_COUNTER_UNIT_MAX_ENUM = 0x7FFFFFFF
} MlnCounterUnit;

typedef enum MlnQueryPoolDescriptorFlagBits {
    MLN_QUERY_POOL_DESCRIPTOR_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} MlnQueryPoolDescriptorFlagBits;

#ifdef __cplusplus
}
#endif
