#version 460 core
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

// specialization

// includes
#include "render/shaders/common/render_compatibility_common.h"

// sets

layout(set = 0, binding = 0, rgba8) uniform writeonly image2D uWoTex;
layout(set = 0, binding = 1) uniform sampler2D uImgSampler;

struct PushDataStruct {
    vec4 texSizeInvSize;
    vec4 color;
};

layout(push_constant) uniform PushConstant
{
    PushDataStruct pc;
};

#define cTgs 8
layout(local_size_x = cTgs, local_size_y = cTgs, local_size_z = 1) in;
void main(void)
{
    const uvec2 texSize = uvec2(pc.texSizeInvSize.xy);
    if ((gl_GlobalInvocationID.x < texSize.x) && (gl_GlobalInvocationID.y < texSize.y)) {
        vec4 color = pc.color;
        color += texelFetch(uImgSampler, ivec2(0, 0), 0);

        imageStore(uWoTex, ivec2(gl_GlobalInvocationID.xy), color);
    }
}
