/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef API_CORE_JSON2_JSON_H
#define API_CORE_JSON2_JSON_H

#include <cstdint>
#include <cstdio>
#include <new>

#include <base/containers/string.h>
#include <base/containers/string_view.h>
#include <base/containers/type_traits.h>
#include <base/containers/vector.h>
#include <base/namespace.h>
#include <core/log.h>

CORE_BEGIN_NAMESPACE()
namespace json2 {

/// # Basic Usage
/// ## Constructing objects:
///
///     ```c++
///     using JSON = CORE_NS::json2::value;
///     auto myObject = JSON::object({
///         { "key1", JSON::string("value") },
///         { "key2", JSON::number(5) },
///         { "key3", JSON::boolean(true) },
///         {
///             "key4",
///             JSON::array({
///                 JSON::number(-1),
///                 JSON::number(3.24),
///             }),
///         },
///     });
///
///     string encoded = myObject.to_string();
///     ```
///
/// ## Parsing objects:
///
///     ```c++
///     string backingStorage = R"( { "hello": "world" } )";
///
///     using JSON = CORE_NS::json2::view; // <- using view to reduce heap allocations
///     JSON jsonView = JSON::parse(backingStorage);
///
///     ASSERT_TRUE(jsonView.is_object());
///     JSON* element = jsonView.find("key");
///     ASSERT_TRUE(element);
///     ASSERT_TRUE(element->is_string());
///
///     string value = element->as_string(); // returns unescaped string
///     ASSERT_STREQ("world", unescaped.c_str());
///
///  # Performance:
///
///  String escaping/unescaping may come with additional heap allocations. Therefore, when
///  using static string keys during lookups (e.g. in .find()), it is recommended to
///  explicitly construct an "already escaped" type by stating our assumption:
///
///     ```c++
///     jsonValue.find(CORE_NS::json2::escaped_string_view("assumed to be \\t escaped"));
///
///     // or:
///
///     using namespace CORE_NS::json2::literals;
///     jsonValue.find("hello\\t"_escaped);
///     ```
///
using readonly_string_t = BASE_NS::string_view;
using writable_string_t = BASE_NS::string;
template <typename T>
using array_t = BASE_NS::vector<T>;

/// Type of a JSON value.
enum class type : uint8_t {
    uninitialized = 0,
    object,
    array,
    string,
    floating_point,
    signed_int,
    unsigned_int,
    boolean,
    null,
};

/// Tag for JSON values which contain read-only strings. The source JSON string must be kept alive while the parsing
/// results are used.
struct readonly_tag {};

/// Tag for JSON values which contain writable strings. Lifetime of the parsing result doens't depend on the source
/// JSON string.
struct writable_tag {};

template <typename T = readonly_tag>
struct value_t;

/// JSON structure which contains read-only strings. The source JSON string must be kept alive until the parsing
/// results are not used.
using view = value_t<readonly_tag>;

/// JSON structure which contains writable strings. String values can be modified and if the instance was generated by
/// the parser, the source string doesn't need to be stored while the instance is used.
using value = value_t<writable_tag>;

/// Returns true iff T is a valid tag (either `readonly_tag` or `writable_tag`).
template <typename T>
constexpr bool is_valid_tag_v = BASE_NS::is_same_v<T, readonly_tag> || BASE_NS::is_same_v<T, writable_tag>;

/// Parses 'data' and returns JSON structure. the value::type will be 'uninitialized' if parsing failed.
///
/// @param data JSON as a null-terminated string.
/// @return Parsed JSON structure.
template <typename T = readonly_tag, typename = BASE_NS::enable_if_t<is_valid_tag_v<T>>>
[[nodiscard]] value_t<T> parse(BASE_NS::string_view data);

/// Converts a JSON structure into a string.
///
/// @param value JSON structure.
/// @return JSON as string.
template <typename T = readonly_tag>
[[nodiscard]] BASE_NS::string to_string(const value_t<T>& value);

template <typename T = readonly_tag>
void to_string(BASE_NS::string& out, const value_t<T>& value);

namespace Detail {

/// Escapes the given string and returns a raw string.
///
/// Note: this is a private implementation detail of the json2 header, use the type-safe `json2::escape` instead.
[[nodiscard]] BASE_NS::string escape(BASE_NS::string_view str);

void unescape(BASE_NS::string& out, BASE_NS::string_view str);

[[nodiscard]] BASE_NS::string unescape(BASE_NS::string_view str);

void escape(BASE_NS::string& out, BASE_NS::string_view str);

}  // namespace Detail

/// Either string or string_view depending on whether we are using a JSON view or value.
template <typename Tag>
using conditionally_writable_string_t =
    typename BASE_NS::conditional_t<BASE_NS::is_same_v<Tag, writable_tag>, writable_string_t, readonly_string_t>;

template <typename Tag>
class escaped_string_template {
public:
    conditionally_writable_string_t<Tag> escaped;

    /// Constructs an escaped_string from an already escaped string.
    [[nodiscard]] explicit escaped_string_template(conditionally_writable_string_t<Tag> escaped)
        : escaped(BASE_NS::move(escaped))
    {}

    /// Escapes the given string.
    ///
    /// Precondition: Tag must be writable_tag.
    [[nodiscard]] static escaped_string_template from_unescaped(BASE_NS::string_view unescapedString)
    {
        static_assert(
            BASE_NS::is_same_v<Tag, writable_tag>, "Cannot store temporary escaped string in read-only JSON value");
        return escaped_string_template(Detail::escape(unescapedString));
    }

    /// The unescaped value of this string.
    [[nodiscard]] BASE_NS::string value() const
    {
        return Detail::unescape(escaped);
    }

    /// Implicit conversion between readable and writable escaped strings.
    template <typename OtherTag>
    operator escaped_string_template<OtherTag>() const
    {
        return escaped_string_template<OtherTag>(conditionally_writable_string_t<OtherTag>(escaped));
    }

    // Explicit rule of 5 to help the compiler:
    escaped_string_template(const escaped_string_template&) = default;
    escaped_string_template(escaped_string_template&&) = default;
    escaped_string_template& operator=(const escaped_string_template&) = default;
    escaped_string_template& operator=(escaped_string_template&&) = default;
    ~escaped_string_template() = default;
};

/// Compares two escaped strings for equality, irrespective of their storage.
///
/// Note: This method is not unicode-aware, strings are compared based on their byte representation.
template <typename Tag1, typename Tag2>
[[nodiscard]] bool operator==(const escaped_string_template<Tag1>& lhs, const escaped_string_template<Tag2>& rhs)
{
    return lhs.escaped == rhs.escaped;
}

/// Compares two escaped strings for non-equality, irrespective of their storage.
///
/// Note: This method is not unicode-aware, strings are compared based on their byte representation.
template <typename Tag1, typename Tag2>
[[nodiscard]] bool operator!=(const escaped_string_template<Tag1>& lhs, const escaped_string_template<Tag2>& rhs)
{
    return !(lhs == rhs);
}
/// A string assumed to be already escaped.
using escaped_string = escaped_string_template<writable_tag>;
using escaped_string_view = escaped_string_template<readonly_tag>;

[[nodiscard]] escaped_string escape(BASE_NS::string_view str);

namespace literals {

/// A literal that is assumed to be already escaped.
escaped_string_view operator""_escaped(const char*, std::size_t);

/// A literal that is assumed to be already escaped.
escaped_string operator""_escaped_value(const char*, std::size_t);

}  // namespace literals

/// JSON value.
template <typename Tag>
struct value_t {
    /// A type which is `json::escaped_string_view` for the readonly JSON views and `json::escaped_string` for
    /// standalone values.
    ///
    /// Used for keys and string values within this type.
    using escaped_string_t = escaped_string_template<Tag>;

    struct Detail {
        /// The opposite tag of this value's tag.
        using other_tag =
            typename BASE_NS::conditional_t<BASE_NS::is_same_v<Tag, writable_tag>, readonly_tag, writable_tag>;
    };

    /// Tag used for JSON null.
    struct null_t {};

    /// A key-value pair in JSON objects.
    struct pair {
        /// Requires `key` not to be escaped yet.
        [[nodiscard]] pair(BASE_NS::string_view unescapedKey, value_t&& value) noexcept
            : escapedKey(escaped_string_t::from_unescaped(unescapedKey)), value(BASE_NS::move(value))
        {}

        [[nodiscard]] pair(escaped_string_t&& escapedKey, value_t&& value)
            : escapedKey(BASE_NS::move(escapedKey)), value(BASE_NS::move(value))
        {}

        escaped_string_t escapedKey;
        value_t value;

        [[nodiscard]] BASE_NS::string key() const
        {
            return escapedKey.value();
        }
    };

    /// Type used for JSON objects.
    using object_t = array_t<pair>;

    /// Type used for JSON arrays.
    using array_t = array_t<value_t>;

    /// Readable and writable value_t's are good friends.
    template <typename Tag2>
    friend struct value_t;

private:
    // Stored fields:

    /// Type of this JSON value.
    type type_{type::uninitialized};

    /// The underlying value, tagged via `type_`.
    union {
        object_t object_;
        array_t array_;
        escaped_string_t escapedString_;
        double float_;
        int64_t signed_;
        uint64_t unsigned_;
        bool boolean_;
    };

    // Constructors:
    struct passkey {};

    /// Constructs an object by sinking a temporary.
    [[nodiscard]] explicit value_t(
        object_t&& value, passkey key) noexcept  // NOLINT(*-rvalue-reference-param-not-moved)
        : type_{type::object}, object_(BASE_NS::move(value))
    {}

    /// Constructs an array by sinking a temporary.
    [[nodiscard]] explicit value_t(array_t&& value, passkey key) noexcept  // NOLINT(*-rvalue-reference-param-not-moved)
        : type_{type::array}, array_(BASE_NS::move(value))
    {}

    /// Constructs a string JSON value by sinking an escaped string value.
    [[nodiscard]] explicit value_t(escaped_string_t&& value, passkey key)  // NOLINT(*-rvalue-reference-param-not-moved)
        : type_(type::string), escapedString_(BASE_NS::move(value))
    {}

    /// Constructs a JSON value from a number.
    template <typename Number,
        typename = BASE_NS::enable_if_t<BASE_NS::is_arithmetic_v<Number> && !BASE_NS::is_same_v<Number, bool>>>
    explicit value_t(Number value, passkey key) noexcept;

    /// Constructs a JSON boolean value.
    [[nodiscard]] explicit value_t(bool value, passkey key) noexcept : type_(type::boolean), boolean_(value){};

    /// Constructs a null JSON value.
    [[nodiscard]] explicit value_t(null_t nullTag, passkey key) noexcept : type_{type::null}
    {}

public:
    /// Creates an uninitialized JSON value.
    [[nodiscard]] value_t() noexcept : type_{type::uninitialized}
    {}  // Implicit, public so the type can be regular.

    // Factory methods:

    /// Constructs a JSON boolean with the given value.
    [[nodiscard]] static value_t boolean(bool value) noexcept;

    /// Constructs a JSON string value by escaping the given string. Requires json2::value.
    [[nodiscard]] static value_t string(BASE_NS::string_view unescaped) noexcept;

    /// Constructs a JSON string value from an already escaped string.
    [[nodiscard]] static value_t escaped_string(escaped_string_t&& escaped) noexcept;
    [[nodiscard]] static value_t escaped_string(const escaped_string_t& escaped) = delete;
    /// Constructs a JSON string value from an already escaped string.
    [[nodiscard]] static value_t escaped_string(conditionally_writable_string_t<Tag>&& escaped) noexcept;
    [[nodiscard]] static value_t escaped_string(const conditionally_writable_string_t<Tag>&) = delete;
    /// Constructs a JSON string value from an already escaped string literal.
    template <size_t N>
    [[nodiscard]] static value_t escaped_string(const char escaped[N]);  // NOLINT(*-avoid-c-arrays)

    /// Constructs a JSON number value.
    template <typename Number, typename = BASE_NS::enable_if_t<BASE_NS::is_arithmetic_v<Number>>>
    [[nodiscard]] static value_t number(Number value) noexcept;

    /// Constructs an empty JSON array value.
    [[nodiscard]] static value_t array() noexcept;

    /// Constructs a JSON array value by sinking a temporary.
    [[nodiscard]] static value_t array(array_t&& value) noexcept;
    [[nodiscard]] static value_t array(const array_t&) = delete;  // Note: Use explicit copy and sink the temporary.

    /// Constructs a JSON object value by sinking a temporary.
    [[nodiscard]] static value_t object(object_t&& value) noexcept;
    /// Constructs an empty JSON object value.
    [[nodiscard]] static value_t object() noexcept;
    // Note: Please perform an explicit copy on the call site, you need to pass a temporary object.
    [[nodiscard]] static value_t object(const object_t&) = delete;

    /// Constructs a null JSON value.
    [[nodiscard]] static value_t null() noexcept;

    /// Constructs an invalid/uninitialized JSON value.
    [[nodiscard]] static value_t uninitialized() noexcept;

    // String conversion

    [[nodiscard]] static value_t parse(BASE_NS::string_view jsonString) noexcept;
    [[nodiscard]] BASE_NS::string to_string() const;

    // Helper overloads for detecting attempts for illegal implicit conversions:

    template <typename T, typename = BASE_NS::enable_if_t<BASE_NS::is_arithmetic_v<T>>>
    value_t(T) = delete;                                       // Use factory method ::number(...) instead.
    value_t(bool) = delete;                                    // Use factory method ::boolean(...) instead.
    value_t(BASE_NS::string_view) = delete;                    // Use factory method ::string(...) instead.
    value_t(BASE_NS::string) = delete;                         // Use factory method ::string(...) instead.
    value_t(object_t) = delete;                                // Use factory method ::object(...) instead.
    value_t(array_t) = delete;                                 // Use factory method ::array(...) instead.
    value_t(escaped_string_t) = delete;                        // Use factory method ::escaped_string(...) instead.
    value_t(const array_t& value, passkey) = delete;           // Requires value to be a temporary.
    value_t(const object_t& value, passkey) = delete;          // Requires value to be a temporary.
    value_t(const escaped_string_t& value, passkey) = delete;  // Requires value to be a temporary.

    // Rule of 5:

    /// Explicit copy constructor - to prevent unintended copies.
    explicit value_t(const value_t& other);  // NOLINT(*-explicit-constructor, *-explicit-conversions)
    /// Copy assignment operator.
    value_t& operator=(const value_t& other);
    /// Move constructor.
    [[nodiscard]] value_t(value_t&& rhs) noexcept;
    /// Move assignment operator.
    value_t& operator=(value_t&& rhs) noexcept;
    /// Destructor.
    ~value_t();

    /// Conversion between writable/readable JSON values.
    template <typename OtherTag>
    explicit operator value_t<OtherTag>() const
    {
        value_t<OtherTag> other;
        other.type_ = type_;
        switch (type_) {
            case type::uninitialized:
                break;
            case type::object:
                new (&other.object_) typename value_t<OtherTag>::object_t(BASE_NS::default_allocator());
                other.object_.reserve(object_.size());
                for (const auto& p : object_) {
                    other.object_.emplace_back(p.escapedKey, value_t<OtherTag>(p.value));
                }
                break;
            case type::array:
                new (&other.array_) typename value_t<OtherTag>::array_t(BASE_NS::default_allocator());
                other.array_.reserve(array_.size());
                for (const auto& v : array_) {
                    other.array_.emplace_back(v);
                }
                break;
            case type::string:
                new (&other.escapedString_) typename value_t<OtherTag>::escaped_string_t(escapedString_);
                break;
            case type::floating_point:
                other.float_ = float_;
                break;
            case type::signed_int:
                other.signed_ = signed_;
                break;
            case type::unsigned_int:
                other.unsigned_ = unsigned_;
                break;
            case type::boolean:
                other.boolean_ = boolean_;
                break;
            case type::null:
                break;
            default:
                CORE_ASSERT_MSG(false, "Unexpected JSON value type");
        }
        return other;
    }

    template <typename T>
    void destroy(T& object)
    {
        object.~T();
    }

    void cleanup()
    {
        switch (type_) {
            case type::uninitialized:
                break;
            case type::object:
                destroy(object_);
                break;
            case type::array:
                destroy(array_);
                break;
            case type::string:
                destroy(escapedString_);
                break;
            case type::floating_point:
                break;
            case type::signed_int:
                break;
            case type::unsigned_int:
                break;
            case type::boolean:
                break;
            case type::null:
                break;
            default:
                CORE_ASSERT_MSG(false, "Unexpected JSON type");
                break;
        }
    }

    [[nodiscard]] type type() const noexcept
    {
        return type_;
    }

    [[nodiscard]] explicit operator bool() const noexcept
    {
        return type_ != type::uninitialized;
    }

    [[nodiscard]] bool is_object() const noexcept
    {
        return type_ == type::object;
    }

    [[nodiscard]] bool is_array() const noexcept
    {
        return type_ == type::array;
    }

    [[nodiscard]] bool is_string() const noexcept
    {
        return type_ == type::string;
    }

    [[nodiscard]] bool is_floating_point() const noexcept
    {
        return type_ == type::floating_point;
    }

    [[nodiscard]] bool is_signed_int() const noexcept
    {
        return type_ == type::signed_int;
    }

    [[nodiscard]] bool is_unsigned_int() const noexcept
    {
        return type_ == type::unsigned_int;
    }

    [[nodiscard]] bool is_number() const noexcept
    {
        return type_ == type::floating_point || type_ == type::signed_int || type_ == type::unsigned_int;
    }

    [[nodiscard]] bool is_boolean() const noexcept
    {
        return type_ == type::boolean;
    }

    [[nodiscard]] bool is_null() const noexcept
    {
        return type_ == type::null;
    }

    [[nodiscard]] bool is_uninitialized() const noexcept
    {
        return type_ == type::uninitialized;
    }

    /// The numeric value of this JSON value, converted to the requested type.
    ///
    /// Precondition: the value's underlying type is numeric (floating_point, signed_int, or unsigned_int).
    template <typename T>
    [[nodiscard]] T as_number() const noexcept
    {
        switch (type_) {
            case type::floating_point:
                return static_cast<T>(float_);
            case type::signed_int:
                return static_cast<T>(signed_);
            case type::unsigned_int:
                return static_cast<T>(unsigned_);
            default:
                CORE_ASSERT_MSG(false, "Expected numeric JSON type.");
                return 0;
        }
    }

    /// Precondition: the value's type is floating_point, without conversion.
    [[nodiscard]] double as_strict_floating_point() const&
    {
        CORE_ASSERT_MSG(is_floating_point(), "Expected JSON floating point value.");
        return float_;
    }
    /// Precondition: the value's type is floating_point, without conversion.
    [[nodiscard]] double& as_strict_floating_point() &
    {
        CORE_ASSERT_MSG(is_floating_point(), "Expected JSON floating point value.");
        return float_;
    }

    /// Precondition: the value's type is signed_int, without conversion.
    [[nodiscard]] int64_t as_strict_signed_int() const&
    {
        CORE_ASSERT_MSG(is_signed_int(), "Expected JSON signed integer value.");
        return signed_;
    }
    /// Precondition: the value's type is signed_int, without conversion.
    [[nodiscard]] int64_t& as_strict_signed_int() &
    {
        CORE_ASSERT_MSG(is_signed_int(), "Expected JSON signed integer value.");
        return signed_;
    }
    /// Precondition: the value's type is unsigned_int, without conversion.
    [[nodiscard]] uint64_t as_strict_unsigned_int() const&
    {
        CORE_ASSERT_MSG(is_unsigned_int(), "Expected JSON unsigned integer value.");
        return unsigned_;
    }
    /// Precondition: the value's type is unsigned_int, without conversion.
    [[nodiscard]] uint64_t& as_strict_unsigned_int() &
    {
        CORE_ASSERT_MSG(is_unsigned_int(), "Expected JSON unsigned integer value.");
        return unsigned_;
    }

    /// Precondition: the value's type is object.
    [[nodiscard]] object_t& as_object() &
    {
        CORE_ASSERT_MSG(is_object(), "Expected JSON object.");
        return object_;
    }
    /// Precondition: the value's type is object.
    [[nodiscard]] const object_t& as_object() const&
    {
        CORE_ASSERT_MSG(is_object(), "Expected JSON object.");
        return object_;
    }

    /// Precondition: the value's type is array.
    [[nodiscard]] array_t& as_array() &
    {
        CORE_ASSERT_MSG(is_array(), "Expected JSON array.");
        return array_;
    }
    /// Precondition: the value's type is array.
    [[nodiscard]] const array_t& as_array() const&
    {
        CORE_ASSERT_MSG(is_array(), "Expected JSON array.");
        return array_;
    }

    /// Precondition: the value's type is string.
    [[nodiscard]] BASE_NS::string as_string() const
    {
        CORE_ASSERT_MSG(is_string(), "Expected JSON string.");
        return escapedString_.value();
    }

    /// Precondition: the value's type is string.
    [[nodiscard]] escaped_string_t& as_escaped_string() &
    {
        CORE_ASSERT_MSG(is_string(), "Expected JSON string.");
        return escapedString_;
    }
    /// Precondition: the value's type is string.
    [[nodiscard]] const escaped_string_t& as_escaped_string() const&
    {
        CORE_ASSERT_MSG(is_string(), "Expected JSON string.");
        return escapedString_;
    }

    /// Precondition: the value's type is boolean.
    [[nodiscard]] bool as_boolean() const
    {
        CORE_ASSERT_MSG(is_boolean(), "Expected JSON boolean.");
        return boolean_;
    }
    /// Precondition: the value's type is boolean.
    [[nodiscard]] bool& as_boolean()
    {
        CORE_ASSERT_MSG(is_boolean(), "Expected JSON boolean.");
        return boolean_;
    }

    /// Finds a value at the given key in the object.
    ///
    /// Returns nullptr if this value is not an object or if the key was not found.
    [[nodiscard]] const value_t* find(BASE_NS::string_view key) const
    {
        return find(escape(key));
    }
    /// Finds a value at the given key in the object.
    ///
    /// Returns nullptr if this value is not an object or if the key was not found.
    [[nodiscard]] value_t* find(BASE_NS::string_view key)
    {
        return find(escape(key));
    }

    /// Finds the value at the given (escaped) key in the object.
    ///
    /// Returns nullptr if this value is not an object or if the key was not found.
    [[nodiscard]] const value_t* find(escaped_string_view escapedKey) const
    {
        if (type_ == type::object) {
            for (auto& t : object_) {
                if (escaped_string_view(t.escapedKey) == escapedKey) {
                    return &t.value;
                }
            }
        }
        return nullptr;
    }

    /// Finds the value at the given (escaped) key in the object.
    ///
    /// Returns nullptr if this value is not an object or if the key was not found.
    [[nodiscard]] value_t* find(escaped_string_view escapedKey)
    {
        if (type_ == type::object) {
            for (auto& t : object_) {
                if (escaped_string_view(t.escapedKey) == escapedKey) {
                    return &t.value;
                }
            }
        }
        return nullptr;
    }

    /// Retrieves the value at the given _unescaped_ key in the standalone_value object.
    ///
    /// If the key does not exist, a new uninitialized value is created at that key.
    ///
    /// Precondition: The value refers to an object.
    template <typename T = Tag, typename = BASE_NS::enable_if_t<BASE_NS::is_same_v<T, writable_tag>>>
    [[nodiscard]] value_t& operator[](const BASE_NS::string_view& key) &
    {
        return operator[](escape(key));
    }

    /// Retrieves the value at the given _escaped_ key in the standalone_value object.
    ///
    /// If the key does not exist, a new uninitialized value is created at that key.
    ///
    /// Precondition: The value refers to an object.
    template <typename T = Tag, typename = BASE_NS::enable_if_t<BASE_NS::is_same_v<T, writable_tag>>>
    [[nodiscard]] value_t& operator[](const escaped_string_view& escapedKey) &
    {
        // Note: This method cannot work safely on read-only views because we need to be able to insert a string key
        // whose lifetime is guaranteed to be the same as the original string we parsed.

        CORE_ASSERT_MSG(is_object(), "Expected JSON object.");
        for (auto& t : object_) {
            if (t.escapedKey == escapedKey) {
                return t.value;
            }
        }

        object_.emplace_back(escaped_string_t(escapedKey), value_t{});
        return object_.back().value;
    }
};
template <typename Tag>
template <typename Number, typename>
value_t<Tag>::value_t(Number value, passkey key) noexcept
{
    if constexpr (BASE_NS::is_floating_point_v<Number>) {
        type_ = type::floating_point;
        float_ = static_cast<double>(value);
    } else if constexpr (BASE_NS::is_signed_v<Number>) {
        type_ = type::signed_int;
        signed_ = static_cast<int64_t>(value);
    } else if constexpr (BASE_NS::is_unsigned_v<Number>) {
        type_ = type::unsigned_int;
        unsigned_ = static_cast<uint64_t>(value);
    }
}
template <typename Tag>
value_t<Tag> value_t<Tag>::boolean(bool value) noexcept
{
    return value_t(value, passkey());
}
template <typename Tag>
value_t<Tag> value_t<Tag>::string(BASE_NS::string_view unescaped) noexcept
{
    static_assert(BASE_NS::is_same_v<Tag, writable_tag>);
    return value_t(escaped_string::from_unescaped(unescaped), passkey());
}
template <typename Tag>
value_t<Tag> value_t<Tag>::escaped_string(escaped_string_t&& escaped) noexcept
{
    return value_t(BASE_NS::move(escaped), passkey());
}
template <typename Tag>
value_t<Tag> value_t<Tag>::escaped_string(conditionally_writable_string_t<Tag>&& escaped) noexcept
{
    return value_t(escaped_string_t(BASE_NS::move(escaped)), passkey());
}
template <typename Tag>
template <size_t N>
value_t<Tag> value_t<Tag>::escaped_string(const char escaped[N])  // NOLINT(*-avoid-c-arrays)
{
    return value_t(conditionally_writable_string_t<Tag>(escaped, BASE_NS::constexpr_strlen(escaped)));
}
template <typename Tag>
template <typename Number, typename>
value_t<Tag> value_t<Tag>::number(Number value) noexcept
{
    return value_t(value, passkey());
}
template <typename Tag>
value_t<Tag> value_t<Tag>::array(array_t&& value) noexcept
{
    return value_t(BASE_NS::move(value), passkey());
}
template <typename Tag>
value_t<Tag> value_t<Tag>::array() noexcept
{
    return value_t(array_t(), passkey());
}
template <typename Tag>
value_t<Tag> value_t<Tag>::object(object_t&& value) noexcept
{
    return value_t(BASE_NS::move(value), passkey());
}
template <typename Tag>
value_t<Tag> value_t<Tag>::object() noexcept
{
    return value_t(object_t(), passkey());
}
template <typename Tag>
value_t<Tag> value_t<Tag>::null() noexcept
{
    return value_t(null_t(), passkey());
}
template <typename Tag>
value_t<Tag> value_t<Tag>::uninitialized() noexcept
{
    return value_t();
}
template <typename Tag>
value_t<Tag> value_t<Tag>::parse(const BASE_NS::string_view jsonString) noexcept
{
    return json2::parse<Tag>(jsonString);
}
template <typename Tag>
BASE_NS::string value_t<Tag>::to_string() const
{
    return CORE_NS::json2::to_string<Tag>(*this);
}

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable : 4583)  // Suppress warning that members' destructors are not called implcitly.
#endif                           // We are calling them in cleanup explicitly.
template <typename Tag>
value_t<Tag>::value_t(const value_t& other) : type_(other.type_)
{
    switch (type_) {
        case type::uninitialized:
            break;
        case type::object:
            new (&object_) object_t(other.object_);
            break;
        case type::array:
            new (&array_) array_t(other.array_);
            break;
        case type::string:
            new (&escapedString_) escaped_string_t(other.escapedString_);
            break;
        case type::floating_point:
            float_ = other.float_;
            break;
        case type::signed_int:
            signed_ = other.signed_;
            break;
        case type::unsigned_int:
            unsigned_ = other.unsigned_;
            break;
        case type::boolean:
            boolean_ = other.boolean_;
            break;
        case type::null:
            break;
        default:
            CORE_ASSERT_MSG(false, "Unexpected JSON type");
            break;
    }
}
template <typename Tag>
value_t<Tag>& value_t<Tag>::operator=(  // NOLINT(*-oop54-cpp) - We did implement self-assignment correctly.
    const value_t& other)
{
    if (this != &other) {
        cleanup();
        type_ = other.type_;
        switch (type_) {
            case type::uninitialized:
                break;
            case type::object:
                new (&object_) object_t(other.object_);
                break;
            case type::array:
                new (&array_) array_t(other.array_);
                break;
            case type::string:
                new (&escapedString_) escaped_string_t(other.escapedString_);
                break;
            case type::floating_point:
                float_ = other.float_;
                break;
            case type::signed_int:
                signed_ = other.signed_;
                break;
            case type::unsigned_int:
                unsigned_ = other.unsigned_;
                break;
            case type::boolean:
                boolean_ = other.boolean_;
                break;
            case type::null:
                break;
            default:
                CORE_ASSERT_MSG(false, "Unexpected JSON type");
                break;
        }
    }
    return *this;
}
template <typename Tag>
value_t<Tag>::value_t(value_t&& rhs) noexcept : type_{BASE_NS::exchange(rhs.type_, type::uninitialized)}
{
    switch (type_) {
        case type::uninitialized:
            break;
        case type::object:
            new (&object_) object_t(BASE_NS::move(rhs.object_));
            break;
        case type::array:
            new (&array_) array_t(BASE_NS::move(rhs.array_));
            break;
        case type::string:
            new (&escapedString_) escaped_string_t(BASE_NS::move(rhs.escapedString_));
            break;
        case type::floating_point:
            float_ = rhs.float_;
            break;
        case type::signed_int:
            signed_ = rhs.signed_;
            break;
        case type::unsigned_int:
            unsigned_ = rhs.unsigned_;
            break;
        case type::boolean:
            boolean_ = rhs.boolean_;
            break;
        case type::null:
            break;
        default:
            CORE_ASSERT_MSG(false, "Unexpected JSON type");
            break;
    }
}
template <typename Tag>
value_t<Tag>& value_t<Tag>::operator=(value_t&& rhs) noexcept
{
    if (this != &rhs) {
        cleanup();
        type_ = BASE_NS::exchange(rhs.type_, type::uninitialized);
        switch (type_) {
            case type::uninitialized:
                break;
            case type::object:
                new (&object_) object_t(BASE_NS::move(rhs.object_));
                break;
            case type::array:
                new (&array_) array_t(BASE_NS::move(rhs.array_));
                break;
            case type::string:
                new (&escapedString_) escaped_string_t(BASE_NS::move(rhs.escapedString_));
                break;
            case type::floating_point:
                float_ = rhs.float_;
                break;
            case type::signed_int:
                signed_ = rhs.signed_;
                break;
            case type::unsigned_int:
                unsigned_ = rhs.unsigned_;
                break;
            case type::boolean:
                boolean_ = rhs.boolean_;
                break;
            case type::null:
                break;
            default:
                CORE_ASSERT_MSG(false, "Unexpected JSON type");
                break;
        }
    }
    return *this;
}
template <typename Tag>
value_t<Tag>::~value_t()
{
    cleanup();
    type_ = type::uninitialized;
}
#ifdef _MSC_VER
#pragma warning(pop)
#endif

/// Checks if two JSON values are equal, irrespective of object key orderings.
///
/// Note: This method is not unicode-aware, strings are compared based on their byte representation.
///
/// Complexity: O(n^2) if the values are objects, where n is the number of key-value pairs in the largest object.
template <typename Tag1, typename Tag2>
[[nodiscard]] bool operator==(const value_t<Tag1>& lhs, const value_t<Tag2>& rhs);

/// Checks if two JSON values are not equal, irrespective of object key orderings.
template <typename Tag1, typename Tag2>
[[nodiscard]] bool operator!=(const value_t<Tag1>& lhs, const value_t<Tag2>& rhs);

// Explicitly require these to be instantiated in the implementation file.
extern template bool operator==
    <readonly_tag, writable_tag>(const value_t<readonly_tag>& lhs, const value_t<writable_tag>& rhs);
extern template bool operator!=
    <readonly_tag, writable_tag>(const value_t<readonly_tag>& lhs, const value_t<writable_tag>& rhs);

extern template bool operator==
    <writable_tag, readonly_tag>(const value_t<writable_tag>& lhs, const value_t<readonly_tag>& rhs);
extern template bool operator!=
    <writable_tag, readonly_tag>(const value_t<writable_tag>& lhs, const value_t<readonly_tag>& rhs);

extern template bool operator==
    <readonly_tag, readonly_tag>(const value_t<readonly_tag>& lhs, const value_t<readonly_tag>& rhs);
extern template bool operator!=
    <readonly_tag, readonly_tag>(const value_t<readonly_tag>& lhs, const value_t<readonly_tag>& rhs);

extern template bool operator==
    <writable_tag, writable_tag>(const value_t<writable_tag>& lhs, const value_t<writable_tag>& rhs);
extern template bool operator!=
    <writable_tag, writable_tag>(const value_t<writable_tag>& lhs, const value_t<writable_tag>& rhs);
}  // namespace json2
CORE_END_NAMESPACE()

#ifdef JSON2_IMPL
#include <charconv>
#include <securec.h>

#include <base/containers/fixed_string.h>
#include <base/util/uid.h>

CORE_BEGIN_NAMESPACE()
namespace json2 {
namespace {
constexpr auto TRUE_STR = BASE_NS::string_view("true");
constexpr auto FALSE_STR = BASE_NS::string_view("false");
constexpr auto NULL_STR = BASE_NS::string_view("null");
constexpr auto UNISTART_STR = BASE_NS::string_view("\\u");

[[nodiscard]] inline bool IsWhite(char data)
{
    return ((data == ' ') || (data == '\n') || (data == '\r') || (data == '\t'));
}

[[nodiscard]] inline bool IsSign(char data)
{
    return ((data == '+') || (data == '-'));
}

[[nodiscard]] inline bool IsDigit(char data)
{
    return ((data >= '0') && (data <= '9'));
}

[[nodiscard]] inline bool IsHex(char data)
{
    return ((data >= '0') && (data <= '9')) || ((data >= 'a') && (data <= 'f')) || ((data >= 'A') && (data <= 'F'));
}

[[nodiscard]] inline BASE_NS::string_view SkipWhiteSpaces(BASE_NS::string_view data)
{
    while (!data.empty() && IsWhite(data.front())) {
        data.remove_prefix(1);
    }
    return data;
}

// values

/// Parses a string literal into `res`, returning the string view of the remainder of the parseable string.
///
/// Expects data to start after the opening "
template <typename Tag>
[[nodiscard]] BASE_NS::string_view parse_string(BASE_NS::string_view data, value_t<Tag>& res)
{
    const auto start = data;
    while (!data.empty()) {
        if (data.front() == '\\' && data.size() >= 2) {
            // escape.. (parse just enough to not stop too early)
            if (data[1] == '\\' || data[1] == '"' || data[1] == '/' || data[1] == 'b' || data[1] == 'f' ||
                data[1] == 'n' || data[1] == 'r' || data[1] == 't') {
                data.remove_prefix(2);
                continue;
            } else if (data[1] == 'u') {
                data.remove_prefix(2);
                if (data.size() < 4) {
                    return data;
                }
                for (char i = 0; i < 4; ++i) {
                    if (data.empty() || !IsHex(data.front())) {
                        // string ended too early or it's an invalid unicode.
                        return data;
                    }
                    data.remove_prefix(1);
                }
            } else {
                // invalid escape
                return data;
            }
        } else if (data.front() == '"') {
            using EscapedString = typename value_t<Tag>::escaped_string_t;
            using String = conditionally_writable_string_t<Tag>;

            res = value_t<Tag>::escaped_string(
                EscapedString(String{start.data(), static_cast<size_t>(data.data() - start.data())}));
            data.remove_prefix(1);
            return data;
        } else if (static_cast<unsigned char>(data.front()) < 0x20) {
            // unexpected unescaped control
            return data;
        } else {
            data.remove_prefix(1);
        }
    }

    // unexpected end
    return data;
}

template <typename Tag>
[[nodiscard]] BASE_NS::string_view parse_number(BASE_NS::string_view data, value_t<Tag>& res)
{
    CORE_ASSERT_MSG(!data.empty() && (IsDigit(data.front()) || IsSign(data.front())),
        "Precondition: first digit is either a digit or a sign");

    bool negative = false;
    const auto beg = data;
    if (data.front() == '-') {
        negative = true;
        data.remove_prefix(1);
        if (data.empty() || !IsDigit(data.front())) {
            // no digits after '-'
            return data;
        }
    }
    bool fraction = false;
    bool exponent = false;

    if (data.front() == '0') {
        data.remove_prefix(1);
        // after leading zero only '.', 'e' and 'E' allowed
        if (!data.empty()) {
            if (data.front() == '.') {
                data.remove_prefix(1);
                fraction = true;
            } else if (data.front() == 'e' || data.front() == 'E') {
                data.remove_prefix(1);
                exponent = true;
            }
        }
    } else {
        while (!data.empty() && IsDigit(data.front())) {
            data.remove_prefix(1);
        }
        if (data.starts_with('.')) {
            data.remove_prefix(1);
            fraction = true;
        } else if (data.starts_with('e') || data.starts_with('E')) {
            data.remove_prefix(1);
            exponent = true;
        }
    }

    if (fraction) {
        // fraction must start with a digit
        if (!data.empty() && IsDigit(data.front())) {
            data.remove_prefix(1);
        } else {
            // fraction missing first digit
            return data;
        }
        // fraction may contain digits up to begining of exponent ('e' or 'E')
        while (!data.empty() && IsDigit(data.front())) {
            data.remove_prefix(1);
        }
        if (data.starts_with('e') || data.starts_with('E')) {
            data.remove_prefix(1);
            exponent = true;
        }
    }
    if (exponent) {
        // exponent must start with '-' or '+' followed by a digit, or digit
        if (data.starts_with('-') || data.starts_with('+')) {
            data.remove_prefix(1);
        }
        if (!data.empty() && IsDigit(data.front())) {
            data.remove_prefix(1);
        } else {
            // exponent missing first digit
            return data;
        }
        while (!data.empty() && IsDigit(data.front())) {
            data.remove_prefix(1);
        }
    }

    if (fraction || exponent) {
        auto distance = data.data() - beg.data();
        if (distance > 64) {
            return data;  // too large number
        }
        BASE_NS::fixed_string<64> stackNullTerminatedString =
            BASE_NS::string_view{beg.data(), static_cast<size_t>(distance)};

        char* pointerAfterParse = nullptr;
        // Assuming this will succeed, as we have already parsed the nummber above.
        double result = std::strtod(stackNullTerminatedString.data(), &pointerAfterParse);
        res = value_t<Tag>::number(result);
        return data;
    } else if (negative) {
        long long result;
        if (std::from_chars(beg.data(), data.data(), result).ec != std::errc{}) {
            return data;
        }
        res = value_t<Tag>::number(result);
        return data;
    }

    unsigned long long result;
    if (std::from_chars(beg.data(), data.data(), result).ec != std::errc{}) {
        return data;
    }
    res = value_t<Tag>::number(result);
    return data;
}

template <typename T>
void add(value_t<T>& v, value_t<T>&& value)
{
    switch (v.type()) {
        case type::uninitialized:
            v = BASE_NS::move(value);
            break;
        case type::object:
            v.as_object().back().value = BASE_NS::move(value);
            break;
        case type::array:
            v.as_array().push_back(BASE_NS::move(value));
            break;
        case type::string:
        case type::floating_point:
        case type::signed_int:
        case type::unsigned_int:
        case type::boolean:
        case type::null:
        default:
            break;
    }
}

}  // namespace

template <typename T, typename>
[[nodiscard]] value_t<T> parse(BASE_NS::string_view data)
{
    using jsonValue = value_t<T>;
    typename jsonValue::array_t stack;
    // push an uninitialized value which will get the final value during parsing
    stack.emplace_back();

    bool acceptValue = true;
    while (!data.empty()) {
        data = SkipWhiteSpaces(data);
        if (data.empty()) {
            return {};  // unexpected end
        }
        if (data.front() == '{') {
            // start of an object
            if (!acceptValue) {
                return {};
            }
            data.remove_prefix(1);
            data = SkipWhiteSpaces(data);
            if (data.starts_with('}')) {
                data.remove_prefix(1);
                data = SkipWhiteSpaces(data);
                // handle empty object.
                add(stack.back(), jsonValue::object());
                acceptValue = false;
            } else if (data.starts_with('"')) {
                // try to read the key
                jsonValue key;
                data.remove_prefix(1);
                data = parse_string(data, key);
                if (!key.is_string()) {
                    return {};  // failed to parse key
                }
                data = SkipWhiteSpaces(data);

                if (!data.starts_with(':')) {
                    // missing : after key
                    return {};
                }
                data.remove_prefix(1);
                data = SkipWhiteSpaces(data);
                // push the object with key and missing value on the stack and hope to find a value next
                stack.emplace_back(jsonValue::object({
                    {BASE_NS::move(key.as_escaped_string()), jsonValue{}},
                }));

                acceptValue = true;
            } else {
                // missing start of key or end of object
                return {};
            }
        } else if (data.front() == '}') {
            // end of an object
            if (stack.back().type() != type::object) {
                // unexpected }
                return {};
            }
            // check are we missing a value ('{"":}', '{"":"",}' )
            if (acceptValue) {
                return {};
            }
            data.remove_prefix(1);
            data = SkipWhiteSpaces(data);
            // move this object to the next in the stack
            auto value = BASE_NS::move(stack.back());
            stack.pop_back();
            if (stack.empty()) {
                // invalid JSON
                return {};
            }
            add(stack.back(), BASE_NS::move(value));
            acceptValue = false;
        } else if (data.front() == '[') {
            // start of an array
            if (!acceptValue) {
                // unexpected [
                return {};
            }
            data.remove_prefix(1);
            data = SkipWhiteSpaces(data);
            if (data.empty()) {
                return {};  // unexpected end
            }
            if (data.front() == ']') {
                data.remove_prefix(1);
                data = SkipWhiteSpaces(data);
                // handle empty array.
                add(stack.back(), jsonValue::array());
                acceptValue = false;
            } else {
                // push the empty array on the stack and hope to find values
                stack.push_back(jsonValue::array());
                acceptValue = true;
            }
        } else if (data.front() == ']') {
            // end of an array
            if (stack.back().type() != type::array) {
                // unexpected ]
                return {};
            }
            // check are we missing a value ('[1,]' '[1]]')
            if (acceptValue) {
                // unexpected ]
                return {};
            }
            data.remove_prefix(1);
            data = SkipWhiteSpaces(data);

            auto value = BASE_NS::move(stack.back());
            stack.pop_back();
            if (stack.empty()) {
                // invalid JSON
                return {};
            }
            add(stack.back(), BASE_NS::move(value));
            acceptValue = false;
        } else if (data.front() == ',') {
            // comma is allowed when the previous value was complete and we have an incomplete object or array on the
            // stack.
            if (!acceptValue && stack.back().type() == type::object) {
                data.remove_prefix(1);
                data = SkipWhiteSpaces(data);
                if (data.empty()) {
                    return {};  // unexpected end
                }
                if (data.front() != '"') {
                    // missing key for next object
                    return {};
                }

                // try to read the key
                jsonValue key;
                data.remove_prefix(1);
                data = parse_string(data, key);
                if (!key.is_string()) {
                    return {};  // failed to parse key
                }
                data = SkipWhiteSpaces(data);

                if (!data.starts_with(':')) {
                    // missing value for next object
                    return {};
                }
                data.remove_prefix(1);
                data = SkipWhiteSpaces(data);
                stack.back().as_object().emplace_back(BASE_NS::move(key.as_escaped_string()), jsonValue{});
                acceptValue = true;
            } else if (!acceptValue && stack.back().type() == type::array) {
                data.remove_prefix(1);
                data = SkipWhiteSpaces(data);
                acceptValue = true;
            } else {
                // comma allowed only between objects and values inside an array
                return {};
            }
        } else if (data.front() == '"') {
            if (!acceptValue) {
                return {};  // unexpeceted "
            }
            jsonValue value;
            data.remove_prefix(1);
            data = parse_string(data, value);
            if (value.type() != type::string) {
                return {};  // invalid string literal
            }

            add(stack.back(), BASE_NS::move(value));
            acceptValue = false;
        } else if (IsSign(data.front()) || IsDigit(data.front())) {
            jsonValue value;
            data = parse_number(data, value);
            if (acceptValue && value.type() != type::uninitialized) {
                add(stack.back(), BASE_NS::move(value));
                acceptValue = false;
            } else {
                // failed parsing number
                return {};
            }
        } else if (data.starts_with(TRUE_STR)) {
            if (!acceptValue) {
                return {};  // value was not expected
            }
            add(stack.back(), jsonValue::boolean(true));
            acceptValue = false;
            data.remove_prefix(TRUE_STR.size());
        } else if (data.starts_with(FALSE_STR)) {
            if (!acceptValue) {
                return {};  // value was not expected
            }
            add(stack.back(), jsonValue::boolean(false));
            acceptValue = false;
            data.remove_prefix(FALSE_STR.size());
        } else if (data.starts_with(NULL_STR)) {
            if (!acceptValue) {
                return {};  // value was not expected
            }
            add(stack.back(), jsonValue::null());
            acceptValue = false;
            data.remove_prefix(NULL_STR.size());
        } else {
            // unexpected character
            return {};
        }
    }
    // check if we are missing a value ('{"":' '[')
    if (acceptValue) {
        return {};
    }

    auto value = BASE_NS::move(stack.front());
    return value;
}

// Explicit instantiations:
template view parse(BASE_NS::string_view);
template value parse(BASE_NS::string_view);
// end of parser
namespace {
/// Requires `escapedString` to be already escaped.
template <typename T>
void append(BASE_NS::string& out, const typename value_t<T>::escaped_string_t& escapedString)
{
    out += '"';
    out += escapedString.escaped;
    out += '"';
}

template <typename T>
void append(BASE_NS::string& out, const typename value_t<T>::object_t& object)
{
    out += '{';
    int count = 0;
    for (const auto& v : object) {
        if (count++) {
            out += ',';
        }
        append<T>(out, v.escapedKey);
        out += ':';
        to_string(out, v.value);
    }
    out += '}';
}

template <typename T>
void append(BASE_NS::string& out, const typename value_t<T>::array_t& array)
{
    out += '[';
    int count = 0;
    for (const auto& v : array) {
        if (count++) {
            out += ',';
        }
        to_string(out, v);
    }
    out += ']';
}

template <typename T>
void append(BASE_NS::string& out, const double floatingPoint)
{
    constexpr const char* FLOATING_FORMAT_STR = "%.17g";
    if (const int size = snprintf(nullptr, 0, FLOATING_FORMAT_STR, floatingPoint); size > 0) {
        const size_t oldSize = out.size();
        out.resize(oldSize + size);
        const size_t newSize = out.size();
        // "At most bufsz - 1 characters are written." string has size() characters + 1 for null so use size() +
        // 1 as the total size. If resize() failed string size() hasn't changed, buffer will point to the null
        // character and bufsz will be 1 i.e. only the null character will be written.
        snprintf_s(
            out.data() + oldSize, newSize + 1 - oldSize, static_cast<size_t>(size), FLOATING_FORMAT_STR, floatingPoint);
    }
}
}  // namespace

template <typename T>
BASE_NS::string to_string(const value_t<T>& value)
{
    BASE_NS::string out;
    to_string(out, value);
    return out;
}

template <typename T>
void to_string(BASE_NS::string& out, const value_t<T>& value)
{
    switch (value.type()) {
        case type::uninitialized:
            break;
        case type::object:
            append<T>(out, value.as_object());
            break;
        case type::array:
            append<T>(out, value.as_array());
            break;
        case type::string:
            append<T>(out, value.as_escaped_string());
            break;
        case type::floating_point:
            append<T>(out, value.as_strict_floating_point());
            break;
        case type::signed_int:
            out += BASE_NS::to_string(value.as_strict_signed_int());
            break;
        case type::unsigned_int:
            out += BASE_NS::to_string(value.as_strict_unsigned_int());
            break;
        case type::boolean:
            if (value.as_boolean()) {
                out += TRUE_STR;
            } else {
                out += FALSE_STR;
            }
            break;
        case type::null:
            out += NULL_STR;
            break;
        default:
            CORE_ASSERT_MSG(false, "Unexpected JSON type");
            break;
    }
}

template BASE_NS::string to_string(const view& value);
template void to_string(BASE_NS::string& out, const view& value);
template BASE_NS::string to_string(const value& value);
template void to_string(BASE_NS::string& out, const value& value);

namespace {
[[nodiscard]] int codepoint(BASE_NS::string_view str)
{
    int code = 0;
    for (size_t u = 0U; u < 4U; ++u) {
        const char chr = str[u];
        code <<= 4;  // Shift by the size of a single hex character
        code += BASE_NS::HexToDec(chr);
    }
    return code;
}
}  // namespace

[[nodiscard]] BASE_NS::string Detail::unescape(BASE_NS::string_view str)
{
    BASE_NS::string unescaped;
    Detail::unescape(unescaped, str);
    return unescaped;
}

void Detail::unescape(BASE_NS::string& out, BASE_NS::string_view str)
{
    out.reserve(out.size() + str.size());
    for (size_t i = 0, end = str.size(); i < end;) {
        auto chr = str[i];
        ++i;
        if (chr != '\\') {
            out += chr;
        } else {
            chr = str[i];
            ++i;
            if (chr == '"') {
                out += '"';  // Quotation mark
            } else if (chr == '\\') {
                out += '\\';  // Reverse solidus
            } else if (chr == '/') {
                out += '/';  // Solidus.. we do unescape this..
            } else if (chr == 'b') {
                out += '\b';  // Backspace
            } else if (chr == 'f') {
                out += '\f';  // Formfeed
            } else if (chr == 'n') {
                out += '\n';  // Linefeed
            } else if (chr == 'r') {
                out += '\r';  // Carriage return
            } else if (chr == 't') {
                out += '\t';            // Horizontal tab
            } else if (chr == 'u') {    // Unicode character
                if ((i + 4U) <= end) {  // Expecting 4 hexadecimal values
                    // Read the Unicode code point.
                    int code = codepoint(str.substr(i, 4U));
                    i += 4U;
                    // Codepoints U+010000 to U+10FFFF are encoded as UTF-16 surrogate pairs. High surrogate between
                    // 0xD800-0xDBFF and low between 0xDC00-0xDFFF.
                    if (code >= 0xd800 && code <= 0xdbff) {
                        // See if there's an other \uXXXX value in the correct range.
                        if ((i + 6U) <= end) {
                            auto next = str.substr(i, 6U);
                            if (next[0] == '\\' && next[1] == 'u') {
                                next.remove_prefix(2);
                                int low = codepoint(next);
                                i += 6U;
                                if (low >= 0xdc00 && low <= 0xdfff) {
                                    // Surrogate pair encoding: 0x10000 + (Hi - 0xD800) * 0x400 + (Lo - 0xDC00)
                                    code = (static_cast<int>(static_cast<unsigned int>(code) << 10U) + low -
                                            (static_cast<int>(0xd800U << 10U) + 0xdc00 - 0x10000));
                                }
                            }
                        }
                    }
                    // Convert code point to UTF-8.
                    if (code < 0x80) {
                        // 1-byte characters: 0xxxxxxx (ASCII)
                        out += static_cast<char>(code);
                    } else if (code < 0x7ff) {
                        // 2-byte characters: 110xxxxx 10xxxxxx
                        out += static_cast<char>(0xc0U | (static_cast<unsigned int>(code) >> 6U));
                        out += static_cast<char>(0x80U | (static_cast<unsigned int>(code) & 0x3fU));
                    } else if (code <= 0xffff) {
                        // 3-byte characters: 1110xxxx 10xxxxxx 10xxxxxx
                        out += static_cast<char>(0xe0U | (static_cast<unsigned int>(code) >> 12u));
                        out += static_cast<char>(0x80U | ((static_cast<unsigned int>(code) >> 6U) & 0x3FU));
                        out += static_cast<char>(0x80U | (static_cast<unsigned int>(code) & 0x3Fu));
                    } else {
                        // 4-byte characters: 11110xxx 10xxxxxx 10xxxxxx 10xxxxxx
                        out += (static_cast<char>(0xf0U | (static_cast<unsigned int>(code) >> 18U)));
                        out += (static_cast<char>(0x80U | ((static_cast<unsigned int>(code) >> 12U) & 0x3fU)));
                        out += (static_cast<char>(0x80U | ((static_cast<unsigned int>(code) >> 6U) & 0x3fU)));
                        out += (static_cast<char>(0x80U | (static_cast<unsigned int>(code) & 0x3fU)));
                    }
                }
            }
        }
    }
}

escaped_string escape(BASE_NS::string_view str)
{
    return escaped_string{Detail::escape(str)};
}

BASE_NS::string Detail::escape(BASE_NS::string_view str)
{
    BASE_NS::string escaped;
    Detail::escape(escaped, str);
    return escaped;
}

void Detail::escape(BASE_NS::string& out, BASE_NS::string_view str)
{
    out.reserve(out.size() + str.size());
    for (size_t i = 0, end = str.size(); i < end;) {
        auto chr = static_cast<uint8_t>(str[i]);
        ++i;
        if (chr == '"') {
            out += "\\\"";  // Quotation mark
        } else if (chr == '\\') {
            out += "\\\\";  // Reverse solidus
        } else if (chr == '\b') {
            out += "\\b";  // Backspace
        } else if (chr == '\f') {
            out += "\\f";  // Formfeed
        } else if (chr == '\n') {
            out += "\\n";  // Linefeed
        } else if (chr == '\r') {
            out += "\\r";  // Carriage return
        } else if (chr == '\t') {
            out += "\\t";  // Horizontal tab
        } else if (chr < 0x80) {
            out += static_cast<BASE_NS::string::value_type>(chr);  // 1-byte characters: 0xxxxxxx (ASCII)
        } else {
            // Unicode
            unsigned code = 0U;
            unsigned left = 0U;
            // Decode first byte and figure out how many additional bytes are needed for the codepoint.
            if (chr < 0xE0) {
                // 2-byte characters: 110xxxxx 10xxxxxx
                if (i < end) {
                    code = ((chr & ~0xC0U));
                    left = 1U;
                }
            } else if (chr < 0xF0) {
                // 3-byte characters: 1110xxxx 10xxxxxx 10xxxxxx
                if ((i + 1U) < end) {
                    code = (chr & ~0xE0U);
                    left = 2U;
                }
            } else if (chr < 0xF8) {
                // 4-byte characters: 11110xxx 10xxxxxx 10xxxxxx 10xxxxxx
                if ((i + 2U) < end) {
                    code = (chr & ~0xF0U);
                    left = 3U;
                }
            }

            // Combine the remaining bytes.
            while (left--) {
                code = (code << 6U) + (str[i++] & 0x3FU);
            }

            // Codepoints U+010000 to U+10FFFF are encoded as UTF-16 surrogate pairs.
            // Surrogate pair encoding: 0x10000 + (Hi - 0xD800) * 0x400 + (Lo - 0xDC00)
            if (code >= 0x010000 && code <= 0x10FFFF) {
                // First append the Hi value.
                code -= 0x10000U;
                const auto hi = (code >> 10U) + 0xD800U;
                out += UNISTART_STR;
                out += BASE_NS::to_hex(hi);

                // Calculate the Lo value.
                code = (code & 0x3FFU) + 0xDC00U;
            }

            // Append the codepoint zero padded to four hex values.
            out += UNISTART_STR;
            const auto codepoint = BASE_NS::to_hex(code);
            if (codepoint.size() < 4U) {
                out.append(4U - codepoint.size(), '0');
            }
            out += codepoint;
        }
    }
}

namespace literals {
escaped_string_view operator""_escaped(const char* str, const std::size_t length)
{
    return escaped_string_view{BASE_NS::string_view{str, length}};
}

escaped_string operator""_escaped_value(const char* str, const std::size_t length)
{
    return escaped_string{BASE_NS::string{str, length}};
}

}  // namespace literals

// Definition of the template operator== for JSON values.
template <typename Tag1, typename Tag2>
bool operator==(const value_t<Tag1>& lhs, const value_t<Tag2>& rhs)
{
    if (lhs.type() != rhs.type()) {
        return false;
    }
    switch (lhs.type()) {
        case type::uninitialized:
            return true;
        case type::object: {
            const auto& lhs_object = lhs.as_object();
            const auto& rhs_object = rhs.as_object();
            if (lhs_object.size() != rhs_object.size()) {
                return false;
            }
            for (const auto& lkv : lhs_object) {
                const auto* matchedValue = rhs.find(lkv.escapedKey);
                if (!matchedValue || (lkv.value != *matchedValue)) {
                    return false;
                }
            }
            for (const auto& rkv : rhs_object) {
                const auto* matchedValue = lhs.find(rkv.escapedKey);
                if (!matchedValue || (rkv.value != *matchedValue)) {
                    return false;
                }
            }
            return true;
        }
        case type::array: {
            const auto& lhs_array = lhs.as_array();
            const auto& rhs_array = rhs.as_array();
            if (lhs_array.size() != rhs_array.size()) {
                return false;
            }
            for (size_t i = 0; i < lhs_array.size(); ++i) {
                if (!(lhs_array[i] == rhs_array[i])) {
                    return false;
                }
            }
            return true;
        }
        case type::string:
            return lhs.as_escaped_string() == rhs.as_escaped_string();
        case type::floating_point:
            return lhs.as_strict_floating_point() == rhs.as_strict_floating_point();
        case type::signed_int:
            return lhs.as_strict_signed_int() == rhs.as_strict_signed_int();
        case type::unsigned_int:
            return lhs.as_strict_unsigned_int() == rhs.as_strict_unsigned_int();
        case type::boolean:
            return lhs.as_boolean() == rhs.as_boolean();
        case type::null:
            return true;
        default:
            CORE_ASSERT_MSG(false, "Unexpected JSON type");
            return false;
    }
}

template <typename Tag1, typename Tag2>
bool operator!=(const value_t<Tag1>& lhs, const value_t<Tag2>& rhs)
{
    return !(lhs == rhs);
}

// Explicit instantiations of all combinations.
// The definitions are placed in the single implementation object file.

template bool operator==
    <readonly_tag, writable_tag>(const value_t<readonly_tag>& lhs, const value_t<writable_tag>& rhs);
template bool operator!=
    <readonly_tag, writable_tag>(const value_t<readonly_tag>& lhs, const value_t<writable_tag>& rhs);

template bool operator==
    <writable_tag, readonly_tag>(const value_t<writable_tag>& lhs, const value_t<readonly_tag>& rhs);
template bool operator!=
    <writable_tag, readonly_tag>(const value_t<writable_tag>& lhs, const value_t<readonly_tag>& rhs);

template bool operator==
    <readonly_tag, readonly_tag>(const value_t<readonly_tag>& lhs, const value_t<readonly_tag>& rhs);
template bool operator!=
    <readonly_tag, readonly_tag>(const value_t<readonly_tag>& lhs, const value_t<readonly_tag>& rhs);

template bool operator==
    <writable_tag, writable_tag>(const value_t<writable_tag>& lhs, const value_t<writable_tag>& rhs);
template bool operator!=
    <writable_tag, writable_tag>(const value_t<writable_tag>& lhs, const value_t<writable_tag>& rhs);

}  // namespace json2
CORE_END_NAMESPACE()
#endif  // JSON2_IMPL

#endif  // !API_CORE_JSON2_JSON_H
