/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Compatibility stubs for taihe types not generated by current IDL toolchain.
 * TODO: Remove once taihe generator produces these types correctly.
 */
#ifndef TAIHE_COMPAT_STUBS_H
#define TAIHE_COMPAT_STUBS_H

#define TAIHE_EFFECTS_CONTAINER_MISSING 1
#define TAIHE_EFFECT_OR_NULL_MISSING 1
#define TAIHE_EFFECT_PROPERTY_VALUES_MISSING 1
#define TAIHE_MAKE_OCCLUSION_MISSING 1

#endif  // TAIHE_COMPAT_STUBS_H
